//! 宿主导入注册表数据（第 5/6 部分）。
//!
//! 按位置拆分，条目顺序不可更改（WASM 函数索引依赖位置）。

use super::{HostImportKey, HostImportSpec};
use super::SpecialHostImport;
use wjsm_ir::Builtin;

/// 第 5 部分：`weakset_proto_add` ~ `typedarray_proto_reduce_right`
pub(crate) static SPECS_PART5: &[HostImportSpec] = &[
    HostImportSpec {
        name: "weakset_proto_add",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakSetProtoAdd)),
        group: None,
    },
    HostImportSpec {
        name: "weakset_proto_has",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakSetProtoHas)),
        group: None,
    },
    HostImportSpec {
        name: "weakset_proto_delete",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakSetProtoDelete)),
        group: None,
    },
    HostImportSpec {
        name: "arraybuffer_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ArrayBufferConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "arraybuffer_proto_byte_length",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ArrayBufferProtoByteLength)),
        group: None,
    },
    HostImportSpec {
        name: "arraybuffer_proto_slice",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::ArrayBufferProtoSlice)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_float64",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetFloat64)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_float32",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetFloat32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_int32",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetInt32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_uint32",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetUint32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_int16",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetInt16)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_uint16",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetUint16)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_int8",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetInt8)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_uint8",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetUint8)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_float64",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetFloat64)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_float32",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetFloat32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_int32",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetInt32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_uint32",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetUint32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_int16",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetInt16)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_uint16",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetUint16)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_int8",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetInt8)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_uint8",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetUint8)),
        group: None,
    },
    HostImportSpec {
        name: "int8array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Int8ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "uint8array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Uint8ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "uint8clampedarray_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(
            Builtin::Uint8ClampedArrayConstructor,
        )),
        group: None,
    },
    HostImportSpec {
        name: "int16array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Int16ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "uint16array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Uint16ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "int32array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Int32ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "uint32array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Uint32ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "float32array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Float32ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "float64array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Float64ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "bigint64array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::BigInt64ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "biguint64array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::BigUint64ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_length",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoLength)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_byte_length",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoByteLength)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_byte_offset",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoByteOffset)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_set",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoSet)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_slice",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoSlice)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_subarray",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoSubarray)),
        group: None,
    },
    HostImportSpec {
        name: "create_global_object",
        type_idx: 4,
        key: Some(HostImportKey::Builtin(Builtin::CreateGlobalObject)),
        group: None,
    },
    HostImportSpec {
        name: "create_exception",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::CreateException)),
        group: None,
    },
    HostImportSpec {
        name: "exception_value",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ExceptionValue)),
        group: None,
    },
    HostImportSpec {
        name: "private_get",
        type_idx: 8,
        key: Some(HostImportKey::Builtin(Builtin::PrivateGet)),
        group: None,
    },
    HostImportSpec {
        name: "private_set",
        type_idx: 32,
        key: Some(HostImportKey::Builtin(Builtin::PrivateSet)),
        group: None,
    },
    HostImportSpec {
        name: "private_has",
        type_idx: 8,
        key: Some(HostImportKey::Builtin(Builtin::PrivateHas)),
        group: None,
    },
    HostImportSpec {
        name: "private_accessor_bind",
        type_idx: 37,
        key: Some(HostImportKey::Builtin(Builtin::PrivateAccessorBind)),
        group: None,
    },
    HostImportSpec {
        name: "proxy_trap_get",
        type_idx: 8,
        key: Some(HostImportKey::Special(SpecialHostImport::ProxyTrapGet)),
        group: None,
    },
    HostImportSpec {
        name: "proxy_trap_set",
        type_idx: 9,
        key: Some(HostImportKey::Special(SpecialHostImport::ProxyTrapSet)),
        group: None,
    },
    HostImportSpec {
        name: "proxy_trap_delete",
        type_idx: 8,
        key: Some(HostImportKey::Special(SpecialHostImport::ProxyTrapDelete)),
        group: None,
    },
    HostImportSpec {
        name: "get_builtin_global",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::GetBuiltinGlobal)),
        group: None,
    },
    HostImportSpec {
        name: "new_target",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NewTarget)),
        group: None,
    },
    HostImportSpec {
        name: "new_target_set",
        type_idx: 3,
        key: Some(HostImportKey::Special(SpecialHostImport::NewTargetSet)),
        group: None,
    },
    HostImportSpec {
        name: "create_unmapped_arguments_object",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(
            Builtin::CreateUnmappedArgumentsObject,
        )),
        group: None,
    },
    HostImportSpec {
        name: "create_mapped_arguments_object",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::CreateMappedArgumentsObject)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_fill",
        type_idx: 17,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoFill)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_reverse",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoReverse)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_index_of",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoIndexOf)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_last_index_of",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoLastIndexOf)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_includes",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoIncludes)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_join",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoJoin)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_to_string",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoToString)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_copy_within",
        type_idx: 17,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoCopyWithin)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_at",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoAt)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_for_each",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoForEach)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_map",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoMap)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_filter",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoFilter)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_reduce",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoReduce)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_reduce_right",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoReduceRight)),
        group: None,
    },
];
