//! 宿主导入注册表数据（第 3/6 部分）。
//!
//! 按位置拆分，条目顺序不可更改（WASM 函数索引依赖位置）。

use super::{HostImportKey, HostImportSpec};
use super::SpecialHostImport;
use wjsm_ir::Builtin;

/// 第 3 部分：`continuation_load_var` ~ `math_cos`
pub(crate) static SPECS_PART3: &[HostImportSpec] = &[
    HostImportSpec {
        name: "continuation_load_var",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ContinuationLoadVar)),
        group: None,
    },
    HostImportSpec {
        name: "async_generator_start",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::AsyncGeneratorStart)),
        group: None,
    },
    HostImportSpec {
        name: "async_generator_next",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::AsyncGeneratorNext)),
        group: None,
    },
    HostImportSpec {
        name: "async_generator_return",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::AsyncGeneratorReturn)),
        group: None,
    },
    HostImportSpec {
        name: "async_generator_throw",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::AsyncGeneratorThrow)),
        group: None,
    },
    HostImportSpec {
        name: "native_call",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::NativeCall)),
        group: None,
    },
    HostImportSpec {
        name: "promise_create_resolve_function",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(
            Builtin::PromiseCreateResolveFunction,
        )),
        group: None,
    },
    HostImportSpec {
        name: "promise_create_reject_function",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::PromiseCreateRejectFunction)),
        group: None,
    },
    HostImportSpec {
        name: "is_callable",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IsCallable)),
        group: None,
    },
    HostImportSpec {
        name: "is_js_object",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IsJsObject)),
        group: None,
    },
    HostImportSpec {
        name: "promise_with_resolvers",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::PromiseWithResolvers)),
        group: None,
    },
    HostImportSpec {
        name: "register_module_namespace",
        type_idx: 5,
        key: Some(HostImportKey::Builtin(Builtin::RegisterModuleNamespace)),
        group: None,
    },
    HostImportSpec {
        name: "dynamic_import",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::DynamicImport)),
        group: None,
    },
    HostImportSpec {
        name: "eval_direct",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::Eval)),
        group: None,
    },
    HostImportSpec {
        name: "eval_indirect",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EvalIndirect)),
        group: None,
    },
    HostImportSpec {
        name: "jsx_create_element",
        type_idx: 27,
        key: Some(HostImportKey::Builtin(Builtin::JsxCreateElement)),
        group: None,
    },
    HostImportSpec {
        name: "proxy_create",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(Builtin::ProxyCreate)),
        group: None,
    },
    HostImportSpec {
        name: "proxy_revocable",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(Builtin::ProxyRevocable)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_get",
        type_idx: 29,
        key: Some(HostImportKey::Builtin(Builtin::ReflectGet)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_set",
        type_idx: 30,
        key: Some(HostImportKey::Builtin(Builtin::ReflectSet)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_has",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(Builtin::ReflectHas)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_delete_property",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(Builtin::ReflectDeleteProperty)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_apply",
        type_idx: 29,
        key: Some(HostImportKey::Builtin(Builtin::ReflectApply)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_construct",
        type_idx: 29,
        key: Some(HostImportKey::Builtin(Builtin::ReflectConstruct)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_get_prototype_of",
        type_idx: 31,
        key: Some(HostImportKey::Builtin(Builtin::ReflectGetPrototypeOf)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_set_prototype_of",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(Builtin::ReflectSetPrototypeOf)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_is_extensible",
        type_idx: 31,
        key: Some(HostImportKey::Builtin(Builtin::ReflectIsExtensible)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_prevent_extensions",
        type_idx: 31,
        key: Some(HostImportKey::Builtin(Builtin::ReflectPreventExtensions)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_get_own_property_descriptor",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(
            Builtin::ReflectGetOwnPropertyDescriptor,
        )),
        group: None,
    },
    HostImportSpec {
        name: "reflect_define_property",
        type_idx: 29,
        key: Some(HostImportKey::Builtin(Builtin::ReflectDefineProperty)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_own_keys",
        type_idx: 31,
        key: Some(HostImportKey::Builtin(Builtin::ReflectOwnKeys)),
        group: None,
    },
    HostImportSpec {
        name: "string_at",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringAt)),
        group: None,
    },
    HostImportSpec {
        name: "string_char_at",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringCharAt)),
        group: None,
    },
    HostImportSpec {
        name: "string_char_code_at",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringCharCodeAt)),
        group: None,
    },
    HostImportSpec {
        name: "string_code_point_at",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringCodePointAt)),
        group: None,
    },
    HostImportSpec {
        name: "string_proto_concat",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::StringConcatVa)),
        group: None,
    },
    HostImportSpec {
        name: "string_ends_with",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringEndsWith)),
        group: None,
    },
    HostImportSpec {
        name: "string_includes",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringIncludes)),
        group: None,
    },
    HostImportSpec {
        name: "string_index_of",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringIndexOf)),
        group: None,
    },
    HostImportSpec {
        name: "string_last_index_of",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringLastIndexOf)),
        group: None,
    },
    HostImportSpec {
        name: "string_match_all",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::StringMatchAll)),
        group: None,
    },
    HostImportSpec {
        name: "string_pad_end",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringPadEnd)),
        group: None,
    },
    HostImportSpec {
        name: "string_pad_start",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringPadStart)),
        group: None,
    },
    HostImportSpec {
        name: "string_repeat",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringRepeat)),
        group: None,
    },
    HostImportSpec {
        name: "string_replace_all",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringReplaceAll)),
        group: None,
    },
    HostImportSpec {
        name: "string_slice",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringSlice)),
        group: None,
    },
    HostImportSpec {
        name: "string_starts_with",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringStartsWith)),
        group: None,
    },
    HostImportSpec {
        name: "string_substring",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringSubstring)),
        group: None,
    },
    HostImportSpec {
        name: "string_to_lower_case",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringToLowerCase)),
        group: None,
    },
    HostImportSpec {
        name: "string_to_upper_case",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringToUpperCase)),
        group: None,
    },
    HostImportSpec {
        name: "string_trim",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringTrim)),
        group: None,
    },
    HostImportSpec {
        name: "string_trim_end",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringTrimEnd)),
        group: None,
    },
    HostImportSpec {
        name: "string_trim_start",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringTrimStart)),
        group: None,
    },
    HostImportSpec {
        name: "string_to_string",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringToString)),
        group: None,
    },
    HostImportSpec {
        name: "string_value_of",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringValueOf)),
        group: None,
    },
    HostImportSpec {
        name: "string_iterator",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringIterator)),
        group: None,
    },
    HostImportSpec {
        name: "string_from_char_code",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::StringFromCharCode)),
        group: None,
    },
    HostImportSpec {
        name: "string_from_code_point",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::StringFromCodePoint)),
        group: None,
    },
    HostImportSpec {
        name: "math_abs",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAbs)),
        group: None,
    },
    HostImportSpec {
        name: "math_acos",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAcos)),
        group: None,
    },
    HostImportSpec {
        name: "math_acosh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAcosh)),
        group: None,
    },
    HostImportSpec {
        name: "math_asin",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAsin)),
        group: None,
    },
    HostImportSpec {
        name: "math_asinh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAsinh)),
        group: None,
    },
    HostImportSpec {
        name: "math_atan",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAtan)),
        group: None,
    },
    HostImportSpec {
        name: "math_atanh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAtanh)),
        group: None,
    },
    HostImportSpec {
        name: "math_atan2",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MathAtan2)),
        group: None,
    },
    HostImportSpec {
        name: "math_cbrt",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathCbrt)),
        group: None,
    },
    HostImportSpec {
        name: "math_ceil",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathCeil)),
        group: None,
    },
    HostImportSpec {
        name: "math_clz32",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathClz32)),
        group: None,
    },
    HostImportSpec {
        name: "math_cos",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathCos)),
        group: None,
    },
];
