//! 宿主导入注册表数据（第 2/6 部分）。
//!
//! 按位置拆分，条目顺序不可更改（WASM 函数索引依赖位置）。

use super::HostImportGroup;
use super::SpecialHostImport;
use super::{HostImportKey, HostImportSpec};
use wjsm_ir::Builtin;

/// 第 2 部分：`arr_proto_reduce_right` ~ `continuation_save_var`
pub(crate) static SPECS_PART2: &[HostImportSpec] = &[
    HostImportSpec {
        name: "arr_proto_reduce_right",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayReduceRight)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_find",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFind)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_find_index",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFindIndex)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_some",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArraySome)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_every",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayEvery)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_flat_map",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFlatMap)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_splice",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArraySpliceVa)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_find_last",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFindLast)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_find_last_index",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFindLastIndex)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_last_index_of",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayLastIndexOf)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_to_sorted",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayToSorted)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_to_reversed",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayToReversed)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_to_spliced",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayToSplicedVa)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_with",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayWith)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_static_is_array",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayIsArray)),
        group: None,
    },
    HostImportSpec {
        name: "arr_static_of",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayOf)),
        group: None,
    },
    HostImportSpec {
        // (i32,i32,i32)->i32 → Type 35
        name: "ensure_shadow_stack_capacity",
        type_idx: 35,
        key: Some(HostImportKey::Builtin(Builtin::EnsureShadowStackCapacity)),
        group: None,
    },
    HostImportSpec {
        name: "func_call",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::FuncCall)),
        group: None,
    },
    HostImportSpec {
        name: "func_apply",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::FuncApply)),
        group: None,
    },
    HostImportSpec {
        name: "func_bind",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::FuncBind)),
        group: None,
    },
    HostImportSpec {
        name: "object_rest",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ObjectRest)),
        group: None,
    },
    HostImportSpec {
        name: "obj_spread",
        type_idx: 5,
        key: Some(HostImportKey::Special(SpecialHostImport::ObjSpread)),
        group: None,
    },
    HostImportSpec {
        name: "has_own_property",
        type_idx: 8,
        key: Some(HostImportKey::Builtin(Builtin::HasOwnProperty)),
        group: None,
    },
    HostImportSpec {
        name: "obj_keys",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectKeys)),
        group: None,
    },
    HostImportSpec {
        name: "obj_values",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectValues)),
        group: None,
    },
    HostImportSpec {
        name: "obj_entries",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectEntries)),
        group: None,
    },
    HostImportSpec {
        name: "obj_assign",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ObjectAssign)),
        group: None,
    },
    HostImportSpec {
        name: "obj_create",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ObjectCreate)),
        group: None,
    },
    HostImportSpec {
        name: "obj_get_proto_of",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectGetPrototypeOf)),
        group: None,
    },
    HostImportSpec {
        name: "obj_set_proto_of",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ObjectSetPrototypeOf)),
        group: None,
    },
    HostImportSpec {
        name: "obj_get_own_prop_names",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectGetOwnPropertyNames)),
        group: None,
    },
    HostImportSpec {
        name: "obj_get_own_prop_symbols",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectGetOwnPropertySymbols)),
        group: None,
    },
    HostImportSpec {
        name: "obj_is",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ObjectIs)),
        group: None,
    },
    HostImportSpec {
        name: "obj_proto_to_string",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectProtoToString)),
        group: None,
    },
    HostImportSpec {
        name: "obj_proto_value_of",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectProtoValueOf)),
        group: None,
    },
    HostImportSpec {
        name: "obj_proto_init",
        type_idx: 3,
        key: Some(HostImportKey::Special(SpecialHostImport::ObjectProtoInit)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_from_literal",
        type_idx: 19,
        key: Some(HostImportKey::Builtin(Builtin::BigIntFromLiteral)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_add",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntAdd)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_sub",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntSub)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_mul",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntMul)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_div",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntDiv)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_mod",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntMod)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_pow",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntPow)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_neg",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::BigIntNeg)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_bit_and",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntBitAnd)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_bit_or",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntBitOr)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_bit_xor",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntBitXor)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_shl",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntShl)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_shr",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntShr)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_bit_not",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::BigIntBitNot)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_eq",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntEq)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_cmp",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntCmp)),
        group: None,
    },
    HostImportSpec {
        name: "symbol_create",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::SymbolCreate)),
        group: None,
    },
    HostImportSpec {
        name: "symbol_for",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::SymbolFor)),
        group: None,
    },
    HostImportSpec {
        name: "symbol_key_for",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::SymbolKeyFor)),
        group: None,
    },
    HostImportSpec {
        name: "symbol_well_known",
        type_idx: 15,
        key: Some(HostImportKey::Builtin(Builtin::SymbolWellKnown)),
        group: None,
    },
    HostImportSpec {
        name: "regex_create",
        type_idx: 20,
        key: Some(HostImportKey::Builtin(Builtin::RegExpCreate)),
        group: None,
    },
    HostImportSpec {
        name: "regex_test",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::RegExpTest)),
        group: None,
    },
    HostImportSpec {
        name: "regex_exec",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::RegExpExec)),
        group: None,
    },
    HostImportSpec {
        name: "string_match",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringMatch)),
        group: None,
    },
    HostImportSpec {
        name: "string_replace",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringReplace)),
        group: None,
    },
    HostImportSpec {
        name: "string_search",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringSearch)),
        group: None,
    },
    HostImportSpec {
        name: "string_split",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringSplit)),
        group: None,
    },
    HostImportSpec {
        name: "promise_create",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::PromiseCreate)),
        group: None,
    },
    HostImportSpec {
        name: "promise_instance_resolve",
        type_idx: 5,
        key: Some(HostImportKey::Builtin(Builtin::PromiseInstanceResolve)),
        group: None,
    },
    HostImportSpec {
        name: "promise_instance_reject",
        type_idx: 5,
        key: Some(HostImportKey::Builtin(Builtin::PromiseInstanceReject)),
        group: None,
    },
    HostImportSpec {
        name: "promise_then",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::PromiseThen)),
        group: None,
    },
    HostImportSpec {
        name: "promise_catch",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseCatch)),
        group: None,
    },
    HostImportSpec {
        name: "promise_finally",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseFinally)),
        group: None,
    },
    HostImportSpec {
        name: "promise_all",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseAll)),
        group: None,
    },
    HostImportSpec {
        name: "promise_race",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseRace)),
        group: None,
    },
    HostImportSpec {
        name: "promise_all_settled",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseAllSettled)),
        group: None,
    },
    HostImportSpec {
        name: "promise_any",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseAny)),
        group: None,
    },
    HostImportSpec {
        name: "promise_resolve_static",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseResolveStatic)),
        group: None,
    },
    HostImportSpec {
        name: "promise_reject_static",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseRejectStatic)),
        group: None,
    },
    HostImportSpec {
        name: "is_promise",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IsPromise)),
        group: None,
    },
    HostImportSpec {
        name: "queue_microtask",
        type_idx: 0,
        key: Some(HostImportKey::Builtin(Builtin::QueueMicrotask)),
        group: None,
    },
    HostImportSpec {
        name: "drain_microtasks",
        type_idx: 1,
        key: Some(HostImportKey::Builtin(Builtin::DrainMicrotasks)),
        group: None,
    },
    HostImportSpec {
        name: "async_function_start",
        type_idx: 21,
        key: Some(HostImportKey::Builtin(Builtin::AsyncFunctionStart)),
        group: None,
    },
    HostImportSpec {
        name: "async_function_resume",
        type_idx: 22,
        key: Some(HostImportKey::Builtin(Builtin::AsyncFunctionResume)),
        group: None,
    },
    HostImportSpec {
        name: "async_function_suspend",
        type_idx: 23,
        key: Some(HostImportKey::Builtin(Builtin::AsyncFunctionSuspend)),
        group: None,
    },
    HostImportSpec {
        name: "continuation_create",
        type_idx: 24,
        key: Some(HostImportKey::Builtin(Builtin::ContinuationCreate)),
        group: None,
    },
    HostImportSpec {
        name: "continuation_save_var",
        type_idx: 25,
        key: Some(HostImportKey::Builtin(Builtin::ContinuationSaveVar)),
        group: None,
    },
];
