//! 宿主导入注册表数据（第 4/6 部分）。
//!
//! 按位置拆分，条目顺序不可更改（WASM 函数索引依赖位置）。

use super::HostImportGroup;
use super::{HostImportKey, HostImportSpec};
use wjsm_ir::Builtin;

/// 第 4 部分：`math_cosh` ~ `weakset_constructor`
pub(crate) static SPECS_PART4: &[HostImportSpec] = &[
    HostImportSpec {
        name: "math_cosh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathCosh)),
        group: None,
    },
    HostImportSpec {
        name: "math_exp",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathExp)),
        group: None,
    },
    HostImportSpec {
        name: "math_expm1",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathExpm1)),
        group: None,
    },
    HostImportSpec {
        name: "math_floor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathFloor)),
        group: None,
    },
    HostImportSpec {
        name: "math_fround",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathFround)),
        group: None,
    },
    HostImportSpec {
        name: "math_hypot",
        type_idx: 19,
        key: Some(HostImportKey::Builtin(Builtin::MathHypot)),
        group: None,
    },
    HostImportSpec {
        name: "math_imul",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MathImul)),
        group: None,
    },
    HostImportSpec {
        name: "math_log",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathLog)),
        group: None,
    },
    HostImportSpec {
        name: "math_log1p",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathLog1p)),
        group: None,
    },
    HostImportSpec {
        name: "math_log10",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathLog10)),
        group: None,
    },
    HostImportSpec {
        name: "math_log2",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathLog2)),
        group: None,
    },
    HostImportSpec {
        name: "math_max",
        type_idx: 19,
        key: Some(HostImportKey::Builtin(Builtin::MathMax)),
        group: None,
    },
    HostImportSpec {
        name: "math_min",
        type_idx: 19,
        key: Some(HostImportKey::Builtin(Builtin::MathMin)),
        group: None,
    },
    HostImportSpec {
        name: "math_pow",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MathPow)),
        group: None,
    },
    HostImportSpec {
        name: "math_random",
        type_idx: 4,
        key: Some(HostImportKey::Builtin(Builtin::MathRandom)),
        group: None,
    },
    HostImportSpec {
        name: "math_round",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathRound)),
        group: None,
    },
    HostImportSpec {
        name: "math_sign",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathSign)),
        group: None,
    },
    HostImportSpec {
        name: "math_sin",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathSin)),
        group: None,
    },
    HostImportSpec {
        name: "math_sinh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathSinh)),
        group: None,
    },
    HostImportSpec {
        name: "math_sqrt",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathSqrt)),
        group: None,
    },
    HostImportSpec {
        name: "math_tan",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathTan)),
        group: None,
    },
    HostImportSpec {
        name: "math_tanh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathTanh)),
        group: None,
    },
    HostImportSpec {
        name: "math_trunc",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathTrunc)),
        group: None,
    },
    HostImportSpec {
        name: "number_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "number_is_nan",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberIsNaN)),
        group: None,
    },
    HostImportSpec {
        name: "number_is_finite",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberIsFinite)),
        group: None,
    },
    HostImportSpec {
        name: "number_is_integer",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberIsInteger)),
        group: None,
    },
    HostImportSpec {
        name: "number_is_safe_integer",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberIsSafeInteger)),
        group: None,
    },
    HostImportSpec {
        name: "number_parse_int",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::NumberParseInt)),
        group: None,
    },
    HostImportSpec {
        name: "number_parse_float",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberParseFloat)),
        group: None,
    },
    HostImportSpec {
        name: "number_proto_to_string",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::NumberProtoToString)),
        group: Some(HostImportGroup::NumberPrototypeMethod),
    },
    HostImportSpec {
        name: "number_proto_value_of",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberProtoValueOf)),
        group: Some(HostImportGroup::NumberPrototypeMethod),
    },
    HostImportSpec {
        name: "number_proto_to_fixed",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::NumberProtoToFixed)),
        group: Some(HostImportGroup::NumberPrototypeMethod),
    },
    HostImportSpec {
        name: "number_proto_to_exponential",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::NumberProtoToExponential)),
        group: Some(HostImportGroup::NumberPrototypeMethod),
    },
    HostImportSpec {
        name: "number_proto_to_precision",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::NumberProtoToPrecision)),
        group: Some(HostImportGroup::NumberPrototypeMethod),
    },
    HostImportSpec {
        name: "boolean_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::BooleanConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "boolean_proto_to_string",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::BooleanProtoToString)),
        group: None,
    },
    HostImportSpec {
        name: "boolean_proto_value_of",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::BooleanProtoValueOf)),
        group: None,
    },
    HostImportSpec {
        name: "error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "type_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypeErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "range_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::RangeErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "syntax_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::SyntaxErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "reference_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ReferenceErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "uri_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::URIErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "eval_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EvalErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "error_proto_to_string",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ErrorProtoToString)),
        group: None,
    },
    HostImportSpec {
        name: "map_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "map_proto_set",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::MapProtoSet)),
        group: None,
    },
    HostImportSpec {
        name: "map_proto_get",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MapProtoGet)),
        group: None,
    },
    HostImportSpec {
        name: "set_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::SetConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "set_proto_add",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::SetProtoAdd)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_has",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MapSetHas)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_delete",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MapSetDelete)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_clear",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapSetClear)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_get_size",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapSetGetSize)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_for_each",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::MapSetForEach)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_keys",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapSetKeys)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_values",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapSetValues)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_entries",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapSetEntries)),
        group: None,
    },
    HostImportSpec {
        name: "date_constructor",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::DateConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "date_now",
        type_idx: 4,
        key: Some(HostImportKey::Builtin(Builtin::DateNow)),
        group: None,
    },
    HostImportSpec {
        name: "date_parse",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::DateParse)),
        group: None,
    },
    HostImportSpec {
        name: "date_utc",
        type_idx: 19,
        key: Some(HostImportKey::Builtin(Builtin::DateUTC)),
        group: None,
    },
    HostImportSpec {
        name: "weakmap_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::WeakMapConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "weakmap_proto_set",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::WeakMapProtoSet)),
        group: None,
    },
    HostImportSpec {
        name: "weakmap_proto_get",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakMapProtoGet)),
        group: None,
    },
    HostImportSpec {
        name: "weakmap_proto_has",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakMapProtoHas)),
        group: None,
    },
    HostImportSpec {
        name: "weakmap_proto_delete",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakMapProtoDelete)),
        group: None,
    },
    HostImportSpec {
        name: "weakset_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::WeakSetConstructor)),
        group: None,
    },
];
