//! 宿主导入注册表数据（第 1/6 部分）。
//!
//! 按位置拆分，条目顺序不可更改（WASM 函数索引依赖位置）。

use super::{HostImportKey, HostImportSpec};
use super::SpecialHostImport;
use super::HostImportGroup;
use wjsm_ir::Builtin;

/// 第 1 部分：`console_log` ~ `arr_proto_reduce`
pub(crate) static SPECS_PART1: &[HostImportSpec] = &[
    HostImportSpec {
        name: "console_log",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleLog)),
        group: None,
    },
    HostImportSpec {
        name: "f64_mod",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::F64Mod)),
        group: None,
    },
    HostImportSpec {
        name: "f64_pow",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::F64Exp)),
        group: None,
    },
    HostImportSpec {
        name: "throw",
        type_idx: 0,
        key: Some(HostImportKey::Builtin(Builtin::Throw)),
        group: None,
    },
    HostImportSpec {
        name: "iterator_from",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IteratorFrom)),
        group: None,
    },
    HostImportSpec {
        name: "iterator_next",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IteratorNext)),
        group: None,
    },
    HostImportSpec {
        name: "iterator_close",
        type_idx: 0,
        key: Some(HostImportKey::Builtin(Builtin::IteratorClose)),
        group: None,
    },
    HostImportSpec {
        name: "iterator_value",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IteratorValue)),
        group: None,
    },
    HostImportSpec {
        name: "iterator_done",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IteratorDone)),
        group: None,
    },
    HostImportSpec {
        name: "enumerator_from",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EnumeratorFrom)),
        group: None,
    },
    HostImportSpec {
        name: "enumerator_next",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EnumeratorNext)),
        group: None,
    },
    HostImportSpec {
        name: "enumerator_key",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EnumeratorKey)),
        group: None,
    },
    HostImportSpec {
        name: "enumerator_done",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EnumeratorDone)),
        group: None,
    },
    HostImportSpec {
        name: "typeof",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypeOf)),
        group: None,
    },
    HostImportSpec {
        name: "op_in",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::In)),
        group: None,
    },
    HostImportSpec {
        name: "op_instanceof",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::InstanceOf)),
        group: None,
    },
    HostImportSpec {
        name: "string_concat",
        type_idx: 11,
        key: Some(HostImportKey::Special(SpecialHostImport::StringConcat)),
        group: None,
    },
    HostImportSpec {
        name: "string_concat_va",
        type_idx: 19,
        key: Some(HostImportKey::Special(SpecialHostImport::StringConcatVa)),
        group: None,
    },
    HostImportSpec {
        name: "define_property",
        type_idx: 32,
        key: Some(HostImportKey::Builtin(Builtin::DefineProperty)),
        group: None,
    },
    HostImportSpec {
        name: "get_own_prop_desc",
        type_idx: 8,
        key: Some(HostImportKey::Builtin(Builtin::GetOwnPropDesc)),
        group: None,
    },
    HostImportSpec {
        name: "abstract_eq",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::AbstractEq)),
        group: None,
    },
    HostImportSpec {
        name: "strict_eq",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StrictEq)),
        group: None,
    },
    HostImportSpec {
        name: "abstract_compare",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::AbstractCompare)),
        group: None,
    },
    HostImportSpec {
        name: "console_error",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleError)),
        group: None,
    },
    HostImportSpec {
        name: "console_warn",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleWarn)),
        group: None,
    },
    HostImportSpec {
        name: "console_info",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleInfo)),
        group: None,
    },
    HostImportSpec {
        name: "console_debug",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleDebug)),
        group: None,
    },
    HostImportSpec {
        name: "console_trace",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleTrace)),
        group: None,
    },
    HostImportSpec {
        name: "set_timeout",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::SetTimeout)),
        group: None,
    },
    HostImportSpec {
        name: "clear_timeout",
        type_idx: 0,
        key: Some(HostImportKey::Builtin(Builtin::ClearTimeout)),
        group: None,
    },
    HostImportSpec {
        name: "set_interval",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::SetInterval)),
        group: None,
    },
    HostImportSpec {
        name: "clear_interval",
        type_idx: 0,
        key: Some(HostImportKey::Builtin(Builtin::ClearInterval)),
        group: None,
    },
    HostImportSpec {
        name: "fetch",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::Fetch)),
        group: None,
    },
    HostImportSpec {
        name: "json_stringify",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::JsonStringify)),
        group: None,
    },
    HostImportSpec {
        name: "json_parse",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::JsonParse)),
        group: None,
    },
    HostImportSpec {
        name: "closure_create",
        type_idx: 2,
        key: Some(HostImportKey::Special(SpecialHostImport::ClosureCreate)),
        group: None,
    },
    HostImportSpec {
        name: "closure_get_func",
        type_idx: 14,
        key: Some(HostImportKey::Special(SpecialHostImport::ClosureGetFunc)),
        group: None,
    },
    HostImportSpec {
        name: "closure_get_env",
        type_idx: 15,
        key: Some(HostImportKey::Special(SpecialHostImport::ClosureGetEnv)),
        group: None,
    },
    HostImportSpec {
        name: "arr_push",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayPush)),
        group: None,
    },
    HostImportSpec {
        name: "array_push_spread",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayPushSpread)),
        group: None,
    },
    HostImportSpec {
        name: "arr_pop",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ArrayPop)),
        group: None,
    },
    HostImportSpec {
        name: "arr_includes",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayIncludes)),
        group: None,
    },
    HostImportSpec {
        name: "arr_index_of",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::ArrayIndexOf)),
        group: None,
    },
    HostImportSpec {
        name: "arr_join",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayJoin)),
        group: None,
    },
    HostImportSpec {
        name: "arr_concat",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayConcat)),
        group: None,
    },
    HostImportSpec {
        name: "arr_slice",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::ArraySlice)),
        group: None,
    },
    HostImportSpec {
        name: "arr_fill",
        type_idx: 17,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFill)),
        group: None,
    },
    HostImportSpec {
        name: "arr_reverse",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ArrayReverse)),
        group: None,
    },
    HostImportSpec {
        name: "arr_flat",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFlat)),
        group: None,
    },
    HostImportSpec {
        name: "arr_init_length",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayInitLength)),
        group: None,
    },
    HostImportSpec {
        name: "arr_get_length",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ArrayGetLength)),
        group: None,
    },
    HostImportSpec {
        name: "arr_proto_push",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::ArrayProtoPush)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_pop",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::ArrayProtoPop)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_includes",
        type_idx: 12,
        key: Some(HostImportKey::Special(
            SpecialHostImport::ArrayProtoIncludes,
        )),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_index_of",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::ArrayProtoIndexOf)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_join",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::ArrayProtoJoin)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_concat",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayConcatVa)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_slice",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::ArrayProtoSlice)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_fill",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::ArrayProtoFill)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_reverse",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::ArrayProtoReverse)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_flat",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::ArrayProtoFlat)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_shift",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayShift)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_unshift",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayUnshiftVa)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_sort",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArraySort)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_at",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayAt)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_copy_within",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayCopyWithin)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_for_each",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayForEach)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_map",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayMap)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_filter",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFilter)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_reduce",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayReduce)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
];
