[package]
name = "wjsm-intl-data"
version.workspace = true
edition.workspace = true

[dependencies]
encoding_rs = { workspace = true }
icu = { version = "=2.2.0", features = ["compiled_data", "unstable"] }
icu_normalizer = { version = "=2.2.0", features = ["compiled_data"] }
idna = "1.1"
sha2 = { workspace = true }
