//! Canonical owner of all host import definitions.
//!
//! This module is the single source of truth for host import names,
//! WASM function type indices, Builtin bindings, special index requirements,
//! and grouping. All other modules derive their knowledge from this registry.
//!
//! Modifying host imports: add/remove/reorder entries here, then
//! update the corresponding runtime host function implementations.

use wjsm_ir::Builtin;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SpecialHostImport {
    ArrayFrom,
    ClosureCreate,
    ClosureGetFunc,
    ClosureGetEnv,
    GcCollect,
    NativeCall,
    NewTargetSet,
    ObjGetByIndex,
    ObjSpread,
    ProxyApply,
    ProxyConstruct,
    ProxyTrapDelete,
    ProxyTrapGet,
    ProxyTrapSet,
    StringConcat,
    StringConcatVa,
    SymbolPropertyKey,
    TypedArraySetByIndex,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HostImportGroup {
    ArrayPrototypeMethod,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HostImportKey {
    Builtin(Builtin),
    Special(SpecialHostImport),
}

#[derive(Debug, Clone, Copy)]
pub struct HostImportSpec {
    pub name: &'static str,
    pub type_idx: u32,
    pub key: Option<HostImportKey>,
    pub group: Option<HostImportGroup>,
}

static HOST_IMPORT_SPECS: &[HostImportSpec] = &[
    HostImportSpec {
        name: "console_log",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleLog)),
        group: None,
    },
    HostImportSpec {
        name: "f64_mod",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::F64Mod)),
        group: None,
    },
    HostImportSpec {
        name: "f64_pow",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::F64Exp)),
        group: None,
    },
    HostImportSpec {
        name: "throw",
        type_idx: 0,
        key: Some(HostImportKey::Builtin(Builtin::Throw)),
        group: None,
    },
    HostImportSpec {
        name: "iterator_from",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IteratorFrom)),
        group: None,
    },
    HostImportSpec {
        name: "iterator_next",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IteratorNext)),
        group: None,
    },
    HostImportSpec {
        name: "iterator_close",
        type_idx: 0,
        key: Some(HostImportKey::Builtin(Builtin::IteratorClose)),
        group: None,
    },
    HostImportSpec {
        name: "iterator_value",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IteratorValue)),
        group: None,
    },
    HostImportSpec {
        name: "iterator_done",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IteratorDone)),
        group: None,
    },
    HostImportSpec {
        name: "enumerator_from",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EnumeratorFrom)),
        group: None,
    },
    HostImportSpec {
        name: "enumerator_next",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EnumeratorNext)),
        group: None,
    },
    HostImportSpec {
        name: "enumerator_key",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EnumeratorKey)),
        group: None,
    },
    HostImportSpec {
        name: "enumerator_done",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EnumeratorDone)),
        group: None,
    },
    HostImportSpec {
        name: "typeof",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypeOf)),
        group: None,
    },
    HostImportSpec {
        name: "op_in",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::In)),
        group: None,
    },
    HostImportSpec {
        name: "op_instanceof",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::InstanceOf)),
        group: None,
    },
    HostImportSpec {
        name: "string_concat",
        type_idx: 11,
        key: Some(HostImportKey::Special(SpecialHostImport::StringConcat)),
        group: None,
    },
    HostImportSpec {
        name: "string_concat_va",
        type_idx: 19,
        key: Some(HostImportKey::Special(SpecialHostImport::StringConcatVa)),
        group: None,
    },
    HostImportSpec {
        name: "define_property",
        type_idx: 9,
        key: Some(HostImportKey::Builtin(Builtin::DefineProperty)),
        group: None,
    },
    HostImportSpec {
        name: "get_own_prop_desc",
        type_idx: 8,
        key: Some(HostImportKey::Builtin(Builtin::GetOwnPropDesc)),
        group: None,
    },
    HostImportSpec {
        name: "abstract_eq",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::AbstractEq)),
        group: None,
    },
    HostImportSpec {
        name: "abstract_compare",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::AbstractCompare)),
        group: None,
    },
    HostImportSpec {
        name: "gc_collect",
        type_idx: 7,
        key: Some(HostImportKey::Special(SpecialHostImport::GcCollect)),
        group: None,
    },
    HostImportSpec {
        name: "console_error",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleError)),
        group: None,
    },
    HostImportSpec {
        name: "console_warn",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleWarn)),
        group: None,
    },
    HostImportSpec {
        name: "console_info",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleInfo)),
        group: None,
    },
    HostImportSpec {
        name: "console_debug",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleDebug)),
        group: None,
    },
    HostImportSpec {
        name: "console_trace",
        type_idx: 33,
        key: Some(HostImportKey::Builtin(Builtin::ConsoleTrace)),
        group: None,
    },
    HostImportSpec {
        name: "set_timeout",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::SetTimeout)),
        group: None,
    },
    HostImportSpec {
        name: "clear_timeout",
        type_idx: 0,
        key: Some(HostImportKey::Builtin(Builtin::ClearTimeout)),
        group: None,
    },
    HostImportSpec {
        name: "set_interval",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::SetInterval)),
        group: None,
    },
    HostImportSpec {
        name: "clear_interval",
        type_idx: 0,
        key: Some(HostImportKey::Builtin(Builtin::ClearInterval)),
        group: None,
    },
    HostImportSpec {
        name: "fetch",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::Fetch)),
        group: None,
    },
    HostImportSpec {
        name: "json_stringify",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::JsonStringify)),
        group: None,
    },
    HostImportSpec {
        name: "json_parse",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::JsonParse)),
        group: None,
    },
    HostImportSpec {
        name: "closure_create",
        type_idx: 13,
        key: Some(HostImportKey::Special(SpecialHostImport::ClosureCreate)),
        group: None,
    },
    HostImportSpec {
        name: "closure_get_func",
        type_idx: 14,
        key: Some(HostImportKey::Special(SpecialHostImport::ClosureGetFunc)),
        group: None,
    },
    HostImportSpec {
        name: "closure_get_env",
        type_idx: 15,
        key: Some(HostImportKey::Special(SpecialHostImport::ClosureGetEnv)),
        group: None,
    },
    HostImportSpec {
        name: "arr_push",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayPush)),
        group: None,
    },
    HostImportSpec {
        name: "arr_pop",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ArrayPop)),
        group: None,
    },
    HostImportSpec {
        name: "arr_includes",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayIncludes)),
        group: None,
    },
    HostImportSpec {
        name: "arr_index_of",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::ArrayIndexOf)),
        group: None,
    },
    HostImportSpec {
        name: "arr_join",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayJoin)),
        group: None,
    },
    HostImportSpec {
        name: "arr_concat",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayConcat)),
        group: None,
    },
    HostImportSpec {
        name: "arr_slice",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::ArraySlice)),
        group: None,
    },
    HostImportSpec {
        name: "arr_fill",
        type_idx: 17,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFill)),
        group: None,
    },
    HostImportSpec {
        name: "arr_reverse",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ArrayReverse)),
        group: None,
    },
    HostImportSpec {
        name: "arr_flat",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFlat)),
        group: None,
    },
    HostImportSpec {
        name: "arr_init_length",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ArrayInitLength)),
        group: None,
    },
    HostImportSpec {
        name: "arr_get_length",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ArrayGetLength)),
        group: None,
    },
    HostImportSpec {
        name: "arr_proto_push",
        type_idx: 12,
        key: None,
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_pop",
        type_idx: 12,
        key: None,
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_includes",
        type_idx: 12,
        key: None,
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_index_of",
        type_idx: 12,
        key: None,
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_join",
        type_idx: 12,
        key: None,
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_concat",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayConcatVa)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_slice",
        type_idx: 12,
        key: None,
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_fill",
        type_idx: 12,
        key: None,
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_reverse",
        type_idx: 12,
        key: None,
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_flat",
        type_idx: 12,
        key: None,
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_shift",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayShift)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_unshift",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayUnshiftVa)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_sort",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArraySort)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_at",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayAt)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_copy_within",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayCopyWithin)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_for_each",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayForEach)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_map",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayMap)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_filter",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFilter)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_reduce",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayReduce)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_reduce_right",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayReduceRight)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_find",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFind)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_find_index",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFindIndex)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_some",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArraySome)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_every",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayEvery)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_flat_map",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFlatMap)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_splice",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArraySpliceVa)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "arr_proto_is_array",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayIsArray)),
        group: Some(HostImportGroup::ArrayPrototypeMethod),
    },
    HostImportSpec {
        name: "abort_shadow_stack_overflow",
        type_idx: 18,
        key: Some(HostImportKey::Builtin(Builtin::AbortShadowStackOverflow)),
        group: None,
    },
    HostImportSpec {
        name: "func_call",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::FuncCall)),
        group: None,
    },
    HostImportSpec {
        name: "func_apply",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::FuncApply)),
        group: None,
    },
    HostImportSpec {
        name: "func_bind",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::FuncBind)),
        group: None,
    },
    HostImportSpec {
        name: "object_rest",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ObjectRest)),
        group: None,
    },
    HostImportSpec {
        name: "obj_spread",
        type_idx: 5,
        key: Some(HostImportKey::Special(SpecialHostImport::ObjSpread)),
        group: None,
    },
    HostImportSpec {
        name: "has_own_property",
        type_idx: 8,
        key: Some(HostImportKey::Builtin(Builtin::HasOwnProperty)),
        group: None,
    },
    HostImportSpec {
        name: "obj_keys",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectKeys)),
        group: None,
    },
    HostImportSpec {
        name: "obj_values",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectValues)),
        group: None,
    },
    HostImportSpec {
        name: "obj_entries",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectEntries)),
        group: None,
    },
    HostImportSpec {
        name: "obj_assign",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ObjectAssign)),
        group: None,
    },
    HostImportSpec {
        name: "obj_create",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ObjectCreate)),
        group: None,
    },
    HostImportSpec {
        name: "obj_get_proto_of",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectGetPrototypeOf)),
        group: None,
    },
    HostImportSpec {
        name: "obj_set_proto_of",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ObjectSetPrototypeOf)),
        group: None,
    },
    HostImportSpec {
        name: "obj_get_own_prop_names",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectGetOwnPropertyNames)),
        group: None,
    },
    HostImportSpec {
        name: "obj_is",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ObjectIs)),
        group: None,
    },
    HostImportSpec {
        name: "obj_proto_to_string",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectProtoToString)),
        group: None,
    },
    HostImportSpec {
        name: "obj_proto_value_of",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectProtoValueOf)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_from_literal",
        type_idx: 19,
        key: Some(HostImportKey::Builtin(Builtin::BigIntFromLiteral)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_add",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntAdd)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_sub",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntSub)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_mul",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntMul)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_div",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntDiv)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_mod",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntMod)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_pow",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntPow)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_neg",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::BigIntNeg)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_eq",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntEq)),
        group: None,
    },
    HostImportSpec {
        name: "bigint_cmp",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::BigIntCmp)),
        group: None,
    },
    HostImportSpec {
        name: "symbol_create",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::SymbolCreate)),
        group: None,
    },
    HostImportSpec {
        name: "symbol_for",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::SymbolFor)),
        group: None,
    },
    HostImportSpec {
        name: "symbol_key_for",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::SymbolKeyFor)),
        group: None,
    },
    HostImportSpec {
        name: "symbol_well_known",
        type_idx: 15,
        key: Some(HostImportKey::Builtin(Builtin::SymbolWellKnown)),
        group: None,
    },
    HostImportSpec {
        name: "regex_create",
        type_idx: 20,
        key: Some(HostImportKey::Builtin(Builtin::RegExpCreate)),
        group: None,
    },
    HostImportSpec {
        name: "regex_test",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::RegExpTest)),
        group: None,
    },
    HostImportSpec {
        name: "regex_exec",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::RegExpExec)),
        group: None,
    },
    HostImportSpec {
        name: "string_match",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringMatch)),
        group: None,
    },
    HostImportSpec {
        name: "string_replace",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringReplace)),
        group: None,
    },
    HostImportSpec {
        name: "string_search",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringSearch)),
        group: None,
    },
    HostImportSpec {
        name: "string_split",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringSplit)),
        group: None,
    },
    HostImportSpec {
        name: "promise_create",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::PromiseCreate)),
        group: None,
    },
    HostImportSpec {
        name: "promise_instance_resolve",
        type_idx: 5,
        key: Some(HostImportKey::Builtin(Builtin::PromiseInstanceResolve)),
        group: None,
    },
    HostImportSpec {
        name: "promise_instance_reject",
        type_idx: 5,
        key: Some(HostImportKey::Builtin(Builtin::PromiseInstanceReject)),
        group: None,
    },
    HostImportSpec {
        name: "promise_then",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::PromiseThen)),
        group: None,
    },
    HostImportSpec {
        name: "promise_catch",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseCatch)),
        group: None,
    },
    HostImportSpec {
        name: "promise_finally",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseFinally)),
        group: None,
    },
    HostImportSpec {
        name: "promise_all",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseAll)),
        group: None,
    },
    HostImportSpec {
        name: "promise_race",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseRace)),
        group: None,
    },
    HostImportSpec {
        name: "promise_all_settled",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseAllSettled)),
        group: None,
    },
    HostImportSpec {
        name: "promise_any",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseAny)),
        group: None,
    },
    HostImportSpec {
        name: "promise_resolve_static",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseResolveStatic)),
        group: None,
    },
    HostImportSpec {
        name: "promise_reject_static",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::PromiseRejectStatic)),
        group: None,
    },
    HostImportSpec {
        name: "is_promise",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IsPromise)),
        group: None,
    },
    HostImportSpec {
        name: "queue_microtask",
        type_idx: 0,
        key: Some(HostImportKey::Builtin(Builtin::QueueMicrotask)),
        group: None,
    },
    HostImportSpec {
        name: "drain_microtasks",
        type_idx: 1,
        key: Some(HostImportKey::Builtin(Builtin::DrainMicrotasks)),
        group: None,
    },
    HostImportSpec {
        name: "async_function_start",
        type_idx: 21,
        key: Some(HostImportKey::Builtin(Builtin::AsyncFunctionStart)),
        group: None,
    },
    HostImportSpec {
        name: "async_function_resume",
        type_idx: 22,
        key: Some(HostImportKey::Builtin(Builtin::AsyncFunctionResume)),
        group: None,
    },
    HostImportSpec {
        name: "async_function_suspend",
        type_idx: 23,
        key: Some(HostImportKey::Builtin(Builtin::AsyncFunctionSuspend)),
        group: None,
    },
    HostImportSpec {
        name: "continuation_create",
        type_idx: 24,
        key: Some(HostImportKey::Builtin(Builtin::ContinuationCreate)),
        group: None,
    },
    HostImportSpec {
        name: "continuation_save_var",
        type_idx: 25,
        key: Some(HostImportKey::Builtin(Builtin::ContinuationSaveVar)),
        group: None,
    },
    HostImportSpec {
        name: "continuation_load_var",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ContinuationLoadVar)),
        group: None,
    },
    HostImportSpec {
        name: "async_generator_start",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::AsyncGeneratorStart)),
        group: None,
    },
    HostImportSpec {
        name: "async_generator_next",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::AsyncGeneratorNext)),
        group: None,
    },
    HostImportSpec {
        name: "async_generator_return",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::AsyncGeneratorReturn)),
        group: None,
    },
    HostImportSpec {
        name: "async_generator_throw",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::AsyncGeneratorThrow)),
        group: None,
    },
    HostImportSpec {
        name: "native_call",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::NativeCall)),
        group: None,
    },
    HostImportSpec {
        name: "promise_create_resolve_function",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(
            Builtin::PromiseCreateResolveFunction,
        )),
        group: None,
    },
    HostImportSpec {
        name: "promise_create_reject_function",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::PromiseCreateRejectFunction)),
        group: None,
    },
    HostImportSpec {
        name: "is_callable",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::IsCallable)),
        group: None,
    },
    HostImportSpec {
        name: "promise_with_resolvers",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::PromiseWithResolvers)),
        group: None,
    },
    HostImportSpec {
        name: "register_module_namespace",
        type_idx: 5,
        key: Some(HostImportKey::Builtin(Builtin::RegisterModuleNamespace)),
        group: None,
    },
    HostImportSpec {
        name: "dynamic_import",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::DynamicImport)),
        group: None,
    },
    HostImportSpec {
        name: "eval_direct",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::Eval)),
        group: None,
    },
    HostImportSpec {
        name: "eval_indirect",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EvalIndirect)),
        group: None,
    },
    HostImportSpec {
        name: "jsx_create_element",
        type_idx: 27,
        key: Some(HostImportKey::Builtin(Builtin::JsxCreateElement)),
        group: None,
    },
    HostImportSpec {
        name: "proxy_create",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(Builtin::ProxyCreate)),
        group: None,
    },
    HostImportSpec {
        name: "proxy_revocable",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(Builtin::ProxyRevocable)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_get",
        type_idx: 29,
        key: Some(HostImportKey::Builtin(Builtin::ReflectGet)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_set",
        type_idx: 30,
        key: Some(HostImportKey::Builtin(Builtin::ReflectSet)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_has",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(Builtin::ReflectHas)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_delete_property",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(Builtin::ReflectDeleteProperty)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_apply",
        type_idx: 29,
        key: Some(HostImportKey::Builtin(Builtin::ReflectApply)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_construct",
        type_idx: 29,
        key: Some(HostImportKey::Builtin(Builtin::ReflectConstruct)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_get_prototype_of",
        type_idx: 31,
        key: Some(HostImportKey::Builtin(Builtin::ReflectGetPrototypeOf)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_set_prototype_of",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(Builtin::ReflectSetPrototypeOf)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_is_extensible",
        type_idx: 31,
        key: Some(HostImportKey::Builtin(Builtin::ReflectIsExtensible)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_prevent_extensions",
        type_idx: 31,
        key: Some(HostImportKey::Builtin(Builtin::ReflectPreventExtensions)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_get_own_property_descriptor",
        type_idx: 28,
        key: Some(HostImportKey::Builtin(
            Builtin::ReflectGetOwnPropertyDescriptor,
        )),
        group: None,
    },
    HostImportSpec {
        name: "reflect_define_property",
        type_idx: 29,
        key: Some(HostImportKey::Builtin(Builtin::ReflectDefineProperty)),
        group: None,
    },
    HostImportSpec {
        name: "reflect_own_keys",
        type_idx: 31,
        key: Some(HostImportKey::Builtin(Builtin::ReflectOwnKeys)),
        group: None,
    },
    HostImportSpec {
        name: "string_at",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringAt)),
        group: None,
    },
    HostImportSpec {
        name: "string_char_at",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringCharAt)),
        group: None,
    },
    HostImportSpec {
        name: "string_char_code_at",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringCharCodeAt)),
        group: None,
    },
    HostImportSpec {
        name: "string_code_point_at",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringCodePointAt)),
        group: None,
    },
    HostImportSpec {
        name: "string_proto_concat",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::StringConcatVa)),
        group: None,
    },
    HostImportSpec {
        name: "string_ends_with",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringEndsWith)),
        group: None,
    },
    HostImportSpec {
        name: "string_includes",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringIncludes)),
        group: None,
    },
    HostImportSpec {
        name: "string_index_of",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringIndexOf)),
        group: None,
    },
    HostImportSpec {
        name: "string_last_index_of",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringLastIndexOf)),
        group: None,
    },
    HostImportSpec {
        name: "string_match_all",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::StringMatchAll)),
        group: None,
    },
    HostImportSpec {
        name: "string_pad_end",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringPadEnd)),
        group: None,
    },
    HostImportSpec {
        name: "string_pad_start",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringPadStart)),
        group: None,
    },
    HostImportSpec {
        name: "string_repeat",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::StringRepeat)),
        group: None,
    },
    HostImportSpec {
        name: "string_replace_all",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringReplaceAll)),
        group: None,
    },
    HostImportSpec {
        name: "string_slice",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringSlice)),
        group: None,
    },
    HostImportSpec {
        name: "string_starts_with",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringStartsWith)),
        group: None,
    },
    HostImportSpec {
        name: "string_substring",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::StringSubstring)),
        group: None,
    },
    HostImportSpec {
        name: "string_to_lower_case",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringToLowerCase)),
        group: None,
    },
    HostImportSpec {
        name: "string_to_upper_case",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringToUpperCase)),
        group: None,
    },
    HostImportSpec {
        name: "string_trim",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringTrim)),
        group: None,
    },
    HostImportSpec {
        name: "string_trim_end",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringTrimEnd)),
        group: None,
    },
    HostImportSpec {
        name: "string_trim_start",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringTrimStart)),
        group: None,
    },
    HostImportSpec {
        name: "string_to_string",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringToString)),
        group: None,
    },
    HostImportSpec {
        name: "string_value_of",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringValueOf)),
        group: None,
    },
    HostImportSpec {
        name: "string_iterator",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::StringIterator)),
        group: None,
    },
    HostImportSpec {
        name: "string_from_char_code",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::StringFromCharCode)),
        group: None,
    },
    HostImportSpec {
        name: "string_from_code_point",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::StringFromCodePoint)),
        group: None,
    },
    HostImportSpec {
        name: "math_abs",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAbs)),
        group: None,
    },
    HostImportSpec {
        name: "math_acos",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAcos)),
        group: None,
    },
    HostImportSpec {
        name: "math_acosh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAcosh)),
        group: None,
    },
    HostImportSpec {
        name: "math_asin",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAsin)),
        group: None,
    },
    HostImportSpec {
        name: "math_asinh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAsinh)),
        group: None,
    },
    HostImportSpec {
        name: "math_atan",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAtan)),
        group: None,
    },
    HostImportSpec {
        name: "math_atanh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathAtanh)),
        group: None,
    },
    HostImportSpec {
        name: "math_atan2",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MathAtan2)),
        group: None,
    },
    HostImportSpec {
        name: "math_cbrt",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathCbrt)),
        group: None,
    },
    HostImportSpec {
        name: "math_ceil",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathCeil)),
        group: None,
    },
    HostImportSpec {
        name: "math_clz32",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathClz32)),
        group: None,
    },
    HostImportSpec {
        name: "math_cos",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathCos)),
        group: None,
    },
    HostImportSpec {
        name: "math_cosh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathCosh)),
        group: None,
    },
    HostImportSpec {
        name: "math_exp",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathExp)),
        group: None,
    },
    HostImportSpec {
        name: "math_expm1",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathExpm1)),
        group: None,
    },
    HostImportSpec {
        name: "math_floor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathFloor)),
        group: None,
    },
    HostImportSpec {
        name: "math_fround",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathFround)),
        group: None,
    },
    HostImportSpec {
        name: "math_hypot",
        type_idx: 19,
        key: Some(HostImportKey::Builtin(Builtin::MathHypot)),
        group: None,
    },
    HostImportSpec {
        name: "math_imul",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MathImul)),
        group: None,
    },
    HostImportSpec {
        name: "math_log",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathLog)),
        group: None,
    },
    HostImportSpec {
        name: "math_log1p",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathLog1p)),
        group: None,
    },
    HostImportSpec {
        name: "math_log10",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathLog10)),
        group: None,
    },
    HostImportSpec {
        name: "math_log2",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathLog2)),
        group: None,
    },
    HostImportSpec {
        name: "math_max",
        type_idx: 19,
        key: Some(HostImportKey::Builtin(Builtin::MathMax)),
        group: None,
    },
    HostImportSpec {
        name: "math_min",
        type_idx: 19,
        key: Some(HostImportKey::Builtin(Builtin::MathMin)),
        group: None,
    },
    HostImportSpec {
        name: "math_pow",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MathPow)),
        group: None,
    },
    HostImportSpec {
        name: "math_random",
        type_idx: 4,
        key: Some(HostImportKey::Builtin(Builtin::MathRandom)),
        group: None,
    },
    HostImportSpec {
        name: "math_round",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathRound)),
        group: None,
    },
    HostImportSpec {
        name: "math_sign",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathSign)),
        group: None,
    },
    HostImportSpec {
        name: "math_sin",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathSin)),
        group: None,
    },
    HostImportSpec {
        name: "math_sinh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathSinh)),
        group: None,
    },
    HostImportSpec {
        name: "math_sqrt",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathSqrt)),
        group: None,
    },
    HostImportSpec {
        name: "math_tan",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathTan)),
        group: None,
    },
    HostImportSpec {
        name: "math_tanh",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathTanh)),
        group: None,
    },
    HostImportSpec {
        name: "math_trunc",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MathTrunc)),
        group: None,
    },
    HostImportSpec {
        name: "number_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "number_is_nan",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberIsNaN)),
        group: None,
    },
    HostImportSpec {
        name: "number_is_finite",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberIsFinite)),
        group: None,
    },
    HostImportSpec {
        name: "number_is_integer",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberIsInteger)),
        group: None,
    },
    HostImportSpec {
        name: "number_is_safe_integer",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberIsSafeInteger)),
        group: None,
    },
    HostImportSpec {
        name: "number_parse_int",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::NumberParseInt)),
        group: None,
    },
    HostImportSpec {
        name: "number_parse_float",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberParseFloat)),
        group: None,
    },
    HostImportSpec {
        name: "number_proto_to_string",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::NumberProtoToString)),
        group: None,
    },
    HostImportSpec {
        name: "number_proto_value_of",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NumberProtoValueOf)),
        group: None,
    },
    HostImportSpec {
        name: "number_proto_to_fixed",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::NumberProtoToFixed)),
        group: None,
    },
    HostImportSpec {
        name: "number_proto_to_exponential",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::NumberProtoToExponential)),
        group: None,
    },
    HostImportSpec {
        name: "number_proto_to_precision",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::NumberProtoToPrecision)),
        group: None,
    },
    HostImportSpec {
        name: "boolean_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::BooleanConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "boolean_proto_to_string",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::BooleanProtoToString)),
        group: None,
    },
    HostImportSpec {
        name: "boolean_proto_value_of",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::BooleanProtoValueOf)),
        group: None,
    },
    HostImportSpec {
        name: "error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "type_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypeErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "range_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::RangeErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "syntax_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::SyntaxErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "reference_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ReferenceErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "uri_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::URIErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "eval_error_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EvalErrorConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "error_proto_to_string",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ErrorProtoToString)),
        group: None,
    },
    HostImportSpec {
        name: "map_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "map_proto_set",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::MapProtoSet)),
        group: None,
    },
    HostImportSpec {
        name: "map_proto_get",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MapProtoGet)),
        group: None,
    },
    HostImportSpec {
        name: "set_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::SetConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "set_proto_add",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::SetProtoAdd)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_has",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MapSetHas)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_delete",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MapSetDelete)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_clear",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapSetClear)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_get_size",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapSetGetSize)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_for_each",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapSetForEach)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_keys",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapSetKeys)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_values",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapSetValues)),
        group: None,
    },
    HostImportSpec {
        name: "map_set_entries",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::MapSetEntries)),
        group: None,
    },
    HostImportSpec {
        name: "date_constructor",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::DateConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "date_now",
        type_idx: 4,
        key: Some(HostImportKey::Builtin(Builtin::DateNow)),
        group: None,
    },
    HostImportSpec {
        name: "date_parse",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::DateParse)),
        group: None,
    },
    HostImportSpec {
        name: "date_utc",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::DateUTC)),
        group: None,
    },
    HostImportSpec {
        name: "weakmap_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::WeakMapConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "weakmap_proto_set",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::WeakMapProtoSet)),
        group: None,
    },
    HostImportSpec {
        name: "weakmap_proto_get",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakMapProtoGet)),
        group: None,
    },
    HostImportSpec {
        name: "weakmap_proto_has",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakMapProtoHas)),
        group: None,
    },
    HostImportSpec {
        name: "weakmap_proto_delete",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakMapProtoDelete)),
        group: None,
    },
    HostImportSpec {
        name: "weakset_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::WeakSetConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "weakset_proto_add",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakSetProtoAdd)),
        group: None,
    },
    HostImportSpec {
        name: "weakset_proto_has",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakSetProtoHas)),
        group: None,
    },
    HostImportSpec {
        name: "weakset_proto_delete",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::WeakSetProtoDelete)),
        group: None,
    },
    HostImportSpec {
        name: "arraybuffer_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ArrayBufferConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "arraybuffer_proto_byte_length",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ArrayBufferProtoByteLength)),
        group: None,
    },
    HostImportSpec {
        name: "arraybuffer_proto_slice",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::ArrayBufferProtoSlice)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_float64",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetFloat64)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_float32",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetFloat32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_int32",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetInt32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_uint32",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetUint32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_int16",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetInt16)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_uint16",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetUint16)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_int8",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetInt8)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_get_uint8",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoGetUint8)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_float64",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetFloat64)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_float32",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetFloat32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_int32",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetInt32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_uint32",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetUint32)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_int16",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetInt16)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_uint16",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetUint16)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_int8",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetInt8)),
        group: None,
    },
    HostImportSpec {
        name: "dataview_proto_set_uint8",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::DataViewProtoSetUint8)),
        group: None,
    },
    HostImportSpec {
        name: "int8array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Int8ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "uint8array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Uint8ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "uint8clampedarray_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(
            Builtin::Uint8ClampedArrayConstructor,
        )),
        group: None,
    },
    HostImportSpec {
        name: "int16array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Int16ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "uint16array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Uint16ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "int32array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Int32ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "uint32array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Uint32ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "float32array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Float32ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "float64array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::Float64ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "bigint64array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::BigInt64ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "biguint64array_constructor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::BigUint64ArrayConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_length",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoLength)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_byte_length",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoByteLength)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_byte_offset",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoByteOffset)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_set",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoSet)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_slice",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoSlice)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_subarray",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoSubarray)),
        group: None,
    },
    HostImportSpec {
        name: "create_global_object",
        type_idx: 4,
        key: Some(HostImportKey::Builtin(Builtin::CreateGlobalObject)),
        group: None,
    },
    HostImportSpec {
        name: "create_exception",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::CreateException)),
        group: None,
    },
    HostImportSpec {
        name: "exception_value",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ExceptionValue)),
        group: None,
    },
    HostImportSpec {
        name: "private_get",
        type_idx: 8,
        key: Some(HostImportKey::Builtin(Builtin::PrivateGet)),
        group: None,
    },
    HostImportSpec {
        name: "private_set",
        type_idx: 32,
        key: Some(HostImportKey::Builtin(Builtin::PrivateSet)),
        group: None,
    },
    HostImportSpec {
        name: "private_has",
        type_idx: 8,
        key: Some(HostImportKey::Builtin(Builtin::PrivateHas)),
        group: None,
    },
    HostImportSpec {
        name: "proxy_trap_get",
        type_idx: 8,
        key: Some(HostImportKey::Special(SpecialHostImport::ProxyTrapGet)),
        group: None,
    },
    HostImportSpec {
        name: "proxy_trap_set",
        type_idx: 9,
        key: Some(HostImportKey::Special(SpecialHostImport::ProxyTrapSet)),
        group: None,
    },
    HostImportSpec {
        name: "proxy_trap_delete",
        type_idx: 8,
        key: Some(HostImportKey::Special(SpecialHostImport::ProxyTrapDelete)),
        group: None,
    },
    HostImportSpec {
        name: "get_builtin_global",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::GetBuiltinGlobal)),
        group: None,
    },
    HostImportSpec {
        name: "new_target",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::NewTarget)),
        group: None,
    },
    HostImportSpec {
        name: "new_target_set",
        type_idx: 3,
        key: Some(HostImportKey::Special(SpecialHostImport::NewTargetSet)),
        group: None,
    },
    HostImportSpec {
        name: "create_unmapped_arguments_object",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(
            Builtin::CreateUnmappedArgumentsObject,
        )),
        group: None,
    },
    HostImportSpec {
        name: "create_mapped_arguments_object",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::CreateMappedArgumentsObject)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_fill",
        type_idx: 17,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoFill)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_reverse",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoReverse)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_index_of",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoIndexOf)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_last_index_of",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoLastIndexOf)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_includes",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoIncludes)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_join",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoJoin)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_to_string",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoToString)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_copy_within",
        type_idx: 17,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoCopyWithin)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_at",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoAt)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_for_each",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoForEach)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_map",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoMap)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_filter",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoFilter)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_reduce",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoReduce)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_reduce_right",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoReduceRight)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_find",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoFind)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_find_index",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoFindIndex)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_some",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoSome)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_every",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoEvery)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_sort",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoSort)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_entries",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoEntries)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_keys",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoKeys)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_proto_values",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::TypedArrayProtoValues)),
        group: None,
    },
    HostImportSpec {
        name: "scope_record_create",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ScopeRecordCreate)),
        group: None,
    },
    HostImportSpec {
        name: "scope_record_add_binding",
        type_idx: 34,
        key: Some(HostImportKey::Builtin(Builtin::ScopeRecordAddBinding)),
        group: None,
    },
    HostImportSpec {
        name: "eval_get_binding",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::EvalGetBinding)),
        group: None,
    },
    HostImportSpec {
        name: "eval_set_binding",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::EvalSetBinding)),
        group: None,
    },
    HostImportSpec {
        name: "eval_has_binding",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::EvalHasBinding)),
        group: None,
    },
    HostImportSpec {
        name: "eval_super_base",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::EvalSuperBase)),
        group: None,
    },
    HostImportSpec {
        name: "scope_record_set_meta",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::ScopeRecordSetMeta)),
        group: None,
    },
    HostImportSpec {
        name: "scope_record_destroy",
        type_idx: 0,
        key: Some(HostImportKey::Builtin(Builtin::ScopeRecordDestroy)),
        group: None,
    },
    HostImportSpec {
        name: "weakref_constructor",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::WeakRefConstructor)),
        group: None,
    },
    HostImportSpec {
        name: "weakref_proto_deref",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::WeakRefProtoDeref)),
        group: None,
    },
    HostImportSpec {
        name: "finalization_registry_constructor",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(
            Builtin::FinalizationRegistryConstructor,
        )),
        group: None,
    },
    HostImportSpec {
        name: "finalization_registry_proto_register",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(
            Builtin::FinalizationRegistryProtoRegister,
        )),
        group: None,
    },
    HostImportSpec {
        name: "finalization_registry_proto_unregister",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(
            Builtin::FinalizationRegistryProtoUnregister,
        )),
        group: None,
    },
    HostImportSpec {
        name: "sharedarraybuffer_constructor",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(
            Builtin::SharedArrayBufferConstructor,
        )),
        group: None,
    },
    HostImportSpec {
        name: "sharedarraybuffer_proto_byte_length",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(
            Builtin::SharedArrayBufferProtoByteLength,
        )),
        group: None,
    },
    HostImportSpec {
        name: "sharedarraybuffer_proto_slice",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::SharedArrayBufferProtoSlice)),
        group: None,
    },
    HostImportSpec {
        name: "sharedarraybuffer_proto_species",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::SharedArrayBufferSpecies)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_load",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsLoad)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_store",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsStore)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_add",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsAdd)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_sub",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsSub)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_and",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsAnd)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_or",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsOr)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_xor",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsXor)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_exchange",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsExchange)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_compare_exchange",
        type_idx: 17,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsCompareExchange)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_is_lock_free",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsIsLockFree)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_wait",
        type_idx: 17,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsWait)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_notify",
        type_idx: 16,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsNotify)),
        group: None,
    },
    HostImportSpec {
        name: "atomics_wait_async",
        type_idx: 17,
        key: Some(HostImportKey::Builtin(Builtin::AtomicsWaitAsync)),
        group: None,
    },
    HostImportSpec {
        name: "async_iterator_from",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::AsyncIteratorFrom)),
        group: None,
    },
    HostImportSpec {
        name: "object.group_by",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::ObjectGroupBy)),
        group: None,
    },
    HostImportSpec {
        name: "map.group_by",
        type_idx: 2,
        key: Some(HostImportKey::Builtin(Builtin::MapGroupBy)),
        group: None,
    },
    HostImportSpec {
        name: "symbol_property_key",
        type_idx: 10,
        key: Some(HostImportKey::Special(SpecialHostImport::SymbolPropertyKey)),
        group: None,
    },
    HostImportSpec {
        name: "array.from",
        type_idx: 12,
        key: Some(HostImportKey::Builtin(Builtin::ArrayFrom)),
        group: None,
    },
    HostImportSpec {
        name: "obj_get_by_index",
        type_idx: 8,
        key: Some(HostImportKey::Special(SpecialHostImport::ObjGetByIndex)),
        group: None,
    },
    HostImportSpec {
        name: "typedarray_set_by_index",
        type_idx: 32,
        key: Some(HostImportKey::Special(
            SpecialHostImport::TypedArraySetByIndex,
        )),
        group: None,
    },
    HostImportSpec {
        name: "object.is_extensible",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectIsExtensible)),
        group: None,
    },
    HostImportSpec {
        name: "object.prevent_extensions",
        type_idx: 3,
        key: Some(HostImportKey::Builtin(Builtin::ObjectPreventExtensions)),
        group: None,
    },
    HostImportSpec {
        name: "proxy.apply",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::ProxyApply)),
        group: None,
    },
    HostImportSpec {
        name: "proxy.construct",
        type_idx: 12,
        key: Some(HostImportKey::Special(SpecialHostImport::ProxyConstruct)),
        group: None,
    },
];

pub fn host_import_specs() -> &'static [HostImportSpec] {
    HOST_IMPORT_SPECS
}
