use std::collections::HashSet;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));

    let suites = ["happy", "errors", "modules"];
    let output_path = manifest_dir
        .join("tests")
        .join("gen")
        .join("generated_fixtures.rs");

    // Collect all fixture paths per suite
    let mut all_cases: Vec<(String, String)> = Vec::new(); // (suite, relative_stem)
    let mut seen_ids: HashSet<String> = HashSet::new();

    for suite in &suites {
        let suite_dir = manifest_dir.join("fixtures").join(suite);
        if !suite_dir.exists() {
            continue;
        }
        collect_fixtures(&suite_dir, &suite_dir, suite, &mut all_cases);
    }

    // Deduplicate by checking sanitized identifiers
    for (suite, stem) in &all_cases {
        let id = sanitize_test_id(suite, stem);
        if !seen_ids.insert(id.clone()) {
            panic!(
                "Duplicate generated test id '{id}' from '{suite}/{stem}'. \
                 Rename one of the conflicting fixture files.",
            );
        }
    }

    // Build output
    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — DO NOT EDIT.\n");
    out.push_str("// Regenerate by: cargo build (triggered automatically on fixture changes)\n\n");
    out.push_str("#![allow(non_snake_case)]\n\n");
    out.push_str("use crate::fixture_runner::FixtureRunner;\n\n");

    for (suite, stem) in &all_cases {
        let id = sanitize_test_id(suite, stem);
        let fixture_path = format!("{suite}/{stem}");
        out.push_str(&format!(
            "#[test]\n\
             fn {id}() {{\n    \
               FixtureRunner::new()\n        \
                 .expect(\"FixtureRunner::new()\")\n        \
                 .run_single(\"{fixture_path}\")\n        \
                 .expect(\"{fixture_path}\");\n\
             }}\n\n",
        ));
    }

    fs::write(&output_path, &out).unwrap_or_else(|e| {
        panic!(
            "Failed to write generated test file at {}: {e}",
            output_path.display()
        );
    });

    // Rerun when fixtures change
    for suite in &suites {
        let dir = manifest_dir.join("fixtures").join(suite);
        if dir.exists() {
            println!("cargo:rerun-if-changed={}", dir.display());
        }
    }
    // Also rerun if the build script itself changes
    println!("cargo:rerun-if-changed=build.rs");
}

fn collect_fixtures(dir: &Path, suite_dir: &Path, suite: &str, cases: &mut Vec<(String, String)>) {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(_) => return,
    };

    let mut entries: Vec<_> = entries.flatten().collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_fixtures(&path, suite_dir, suite, cases);
        } else {
            let ext = path.extension().and_then(|e| e.to_str());
            if ext != Some("js") && ext != Some("ts") {
                continue;
            }

            // 只为有 .expected 快照的 fixture 生成测试
            // 没有 .expected 的文件不是独立可运行的入口（例如 CJS 循环依赖中的非入口模块）
            let expected_path = path.with_extension("expected");
            if !expected_path.exists() {
                continue;
            }

            let relative = path.strip_prefix(suite_dir).unwrap().with_extension("");
            let stem = relative.to_str().unwrap().to_string();
            cases.push((suite.to_string(), stem));
        }
    }
}

/// Build a valid Rust identifier for a test function.
/// Format: `{suite}__{stem}` where non-alphanumeric chars in stem become `_`.
fn sanitize_test_id(suite: &str, stem: &str) -> String {
    let sanitized: String = stem
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    format!("{suite}__{sanitized}")
}
