[package]
name = "wjsm-cli"
version.workspace = true
edition.workspace = true

[features]
default = []

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
wjsm-artifact-format = { path = "../wjsm-artifact-format" }
wjsm-backend-native = { path = "../wjsm-backend-native" }
wjsm-host-native = { path = "../wjsm-host-native" }
wjsm-ir = { path = "../wjsm-ir" }
wjsm-parser = { path = "../wjsm-parser" }
wjsm-gc = { path = "../wjsm-gc" }
wjsm-runtime = { path = "../wjsm-runtime" }
wjsm-semantic = { path = "../wjsm-semantic" }
wjsm-module = { path = "../wjsm-module" }
colored = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
notify = { workspace = true }
swc_core = { workspace = true }
regex = "1"
walkdir = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
flate2 = { workspace = true }
tar = { workspace = true }
