[package]
name = "wjsm-module"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
bincode = { version = "2", features = ["serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
swc_core = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
wjsm-artifact-format = { path = "../wjsm-artifact-format" }
wjsm-parser = { path = "../wjsm-parser" }
wjsm-semantic = { path = "../wjsm-semantic" }
wjsm-ir = { path = "../wjsm-ir" }

[dev-dependencies]
parking_lot = "0.12"
