use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Builtin {
    ConsoleLog,
    ConsoleError,
    ConsoleWarn,
    ConsoleInfo,
    ConsoleDebug,
    ConsoleTrace,
    Debugger,
    Throw,
    AbortShadowStackOverflow,
    F64Mod,
    F64Exp,
    IteratorFrom,
    IteratorNext,
    IteratorClose,
    AsyncIteratorFrom,
    IteratorValue,
    IteratorDone,
    EnumeratorFrom,
    EnumeratorNext,
    EnumeratorKey,
    EnumeratorDone,
    // 运算符
    TypeOf,
    In,
    InstanceOf,
    AbstractEq,
    AbstractCompare,
    // 对象属性描述符
    DefineProperty,
    GetOwnPropDesc,
    // 宿主 API
    SetTimeout,
    ClearTimeout,
    SetInterval,
    ClearInterval,
    Fetch,
    Eval,
    EvalIndirect,
    EvalResult,
    JsonStringify,
    JsonParse,
    CreateClosure,
    // 数组方法
    ArrayPush,
    ArrayPop,
    ArrayIncludes,
    ArrayIndexOf,
    ArrayJoin,
    ArrayConcat,
    ArraySlice,
    ArrayFill,
    ArrayReverse,
    ArrayFlat,
    ArrayInitLength,
    ArrayGetLength,
    // ── 新数组方法 ──
    ArrayShift,
    ArrayUnshiftVa,
    ArraySort,
    ArrayAt,
    ArrayCopyWithin,
    ArrayForEach,
    ArrayMap,
    ArrayFilter,
    ArrayReduce,
    ArrayReduceRight,
    ArrayFind,
    ArrayFindIndex,
    ArraySome,
    ArrayEvery,
    ArrayFlatMap,
    ArrayIsArray,
    ArrayFrom,
    ArraySpliceVa,
    ArrayConcatVa,
    // ── 函数原型方法 ──
    FuncCall,
    FuncApply,
    FuncBind,
    // ── 对象解构 rest ──
    ObjectRest,
    // ── new.prototype 修复 ──
    GetPrototypeFromConstructor,
    // ── Object 原型方法 ──
    HasOwnProperty,
    PrivateGet,
    PrivateSet,
    PrivateHas,
    ObjectProtoToString,
    ObjectProtoValueOf,
    // ── Object 静态方法 ──
    ObjectKeys,
    ObjectValues,
    ObjectEntries,
    ObjectAssign,
    ObjectCreate,
    ObjectGetPrototypeOf,
    ObjectSetPrototypeOf,
    ObjectGetOwnPropertyNames,
    ObjectIs,
    ObjectGroupBy,
    // ── Map.groupBy ──
    MapGroupBy,
    // ── BigInt operations ──────────────────────────────────────────────
    BigIntFromLiteral,
    BigIntAdd,
    BigIntSub,
    BigIntMul,
    BigIntDiv,
    BigIntMod,
    BigIntPow,
    BigIntNeg,
    BigIntEq,
    BigIntCmp,
    // ── Symbol operations ──────────────────────────────────────────────
    SymbolCreate,
    SymbolFor,
    SymbolKeyFor,
    // ── Well-known symbols ─────────────────────────────────────────────
    SymbolWellKnown,
    // ── RegExp operations ──────────────────────────────────────────────
    RegExpCreate,
    RegExpTest,
    RegExpExec,
    // ── String prototype methods ───────────────────────────────────────
    StringMatch,
    StringReplace,
    StringSearch,
    StringSplit,
    PromiseCreate,
    PromiseInstanceResolve,
    PromiseInstanceReject,
    PromiseCreateResolveFunction,
    PromiseCreateRejectFunction,
    PromiseThen,
    PromiseCatch,
    PromiseFinally,
    PromiseAll,
    PromiseRace,
    PromiseAllSettled,
    PromiseAny,
    PromiseResolveStatic,
    PromiseRejectStatic,
    IsPromise,
    QueueMicrotask,
    DrainMicrotasks,
    AsyncFunctionStart,
    AsyncFunctionResume,
    AsyncFunctionSuspend,
    ContinuationCreate,
    ContinuationSaveVar,
    ContinuationLoadVar,
    AsyncGeneratorStart,
    AsyncGeneratorNext,
    AsyncGeneratorReturn,
    AsyncGeneratorThrow,
    PromiseWithResolvers,
    IsCallable,
    // ── 动态 import ──────────────────────────────────────────────────
    DynamicImport,
    RegisterModuleNamespace,
    // ── JSX ────────────────────────────────────────────────────────────
    JsxCreateElement,
    // ── Proxy / Reflect ────────────────────────────────────────────────
    ProxyCreate,
    ProxyRevocable,
    ReflectGet,
    ReflectSet,
    ReflectHas,
    ReflectDeleteProperty,
    ReflectApply,
    ReflectConstruct,
    ReflectGetPrototypeOf,
    ReflectSetPrototypeOf,
    ReflectIsExtensible,
    ReflectPreventExtensions,
    ReflectGetOwnPropertyDescriptor,
    ReflectDefineProperty,
    ReflectOwnKeys,
    // ── String 完整方法 ──
    StringAt,
    StringCharAt,
    StringCharCodeAt,
    StringCodePointAt,
    StringConcatVa,
    StringEndsWith,
    StringIncludes,
    StringIndexOf,
    StringLastIndexOf,
    StringMatchAll,
    StringPadEnd,
    StringPadStart,
    StringRepeat,
    StringReplaceAll,
    StringSlice,
    StringStartsWith,
    StringSubstring,
    StringToLowerCase,
    StringToUpperCase,
    StringTrim,
    StringTrimEnd,
    StringTrimStart,
    StringToString,
    StringValueOf,
    StringIterator,
    StringFromCharCode,
    StringFromCodePoint,
    // ── Math static methods ────────────────────────────────────────────
    MathAbs,
    MathAcos,
    MathAcosh,
    MathAsin,
    MathAsinh,
    MathAtan,
    MathAtanh,
    MathAtan2,
    MathCbrt,
    MathCeil,
    MathClz32,
    MathCos,
    MathCosh,
    MathExp,
    MathExpm1,
    MathFloor,
    MathFround,
    MathHypot,
    MathImul,
    MathLog,
    MathLog1p,
    MathLog10,
    MathLog2,
    MathMax,
    MathMin,
    MathPow,
    MathRandom,
    MathRound,
    MathSign,
    MathSin,
    MathSinh,
    MathSqrt,
    MathTan,
    MathTanh,
    MathTrunc,
    // ── Number built-in ────────────────────────────────────────────────
    NumberConstructor,
    NumberIsNaN,
    NumberIsFinite,
    NumberIsInteger,
    NumberIsSafeInteger,
    NumberParseInt,
    NumberParseFloat,
    NumberProtoToString,
    NumberProtoValueOf,
    NumberProtoToFixed,
    NumberProtoToExponential,
    NumberProtoToPrecision,
    // ── Boolean built-in ───────────────────────────────────────────────
    BooleanConstructor,
    BooleanProtoToString,
    BooleanProtoValueOf,
    // ── Error built-in ─────────────────────────────────────────────────
    ErrorConstructor,
    TypeErrorConstructor,
    RangeErrorConstructor,
    SyntaxErrorConstructor,
    ReferenceErrorConstructor,
    URIErrorConstructor,
    EvalErrorConstructor,
    ErrorProtoToString,
    // ── Map built-in ──────────────────────────────────────────────────
    MapConstructor,
    MapProtoSet,
    MapProtoGet,
    // ── Set built-in ──────────────────────────────────────────────────
    SetConstructor,
    SetProtoAdd,
    // ── Map/Set shared methods (dispatch at runtime) ──────────────────
    MapSetHas,
    MapSetDelete,
    MapSetClear,
    MapSetGetSize,
    MapSetForEach,
    MapSetKeys,
    MapSetValues,
    MapSetEntries,
    // ── Date built-in ─────────────────────────────────────────────────
    DateConstructor,
    DateNow,
    DateParse,
    DateUTC,
    // ── WeakMap built-in ──────────────────────────────────────────────
    WeakMapConstructor,
    WeakMapProtoSet,
    WeakMapProtoGet,
    WeakMapProtoHas,
    WeakMapProtoDelete,
    // ── WeakSet built-in ──────────────────────────────────────────────
    WeakSetConstructor,
    WeakSetProtoAdd,
    WeakSetProtoHas,
    WeakSetProtoDelete,
    // ── SharedArrayBuffer built-in ──
    SharedArrayBufferConstructor,
    SharedArrayBufferProtoByteLength,
    SharedArrayBufferProtoSlice,
    SharedArrayBufferSpecies,
    // ── Atomics built-in ──
    AtomicsLoad,
    AtomicsStore,
    AtomicsAdd,
    AtomicsSub,
    AtomicsAnd,
    AtomicsOr,
    AtomicsXor,
    AtomicsExchange,
    AtomicsCompareExchange,
    AtomicsIsLockFree,
    AtomicsWait,
    AtomicsNotify,
    AtomicsWaitAsync,
    // ── WeakRef built-in ──────────────────────────────────────────────
    WeakRefConstructor,
    WeakRefProtoDeref,
    // ── FinalizationRegistry built-in ─────────────────────────────────
    FinalizationRegistryConstructor,
    FinalizationRegistryProtoRegister,
    FinalizationRegistryProtoUnregister,
    // ── ArrayBuffer built-in ──────────────────────────────────────────
    ArrayBufferConstructor,
    ArrayBufferProtoByteLength,
    ArrayBufferProtoSlice,
    // ── DataView built-in ──────────────────────────────────────────────
    DataViewConstructor,
    DataViewProtoGetFloat64,
    DataViewProtoGetFloat32,
    DataViewProtoGetInt32,
    DataViewProtoGetUint32,
    DataViewProtoGetInt16,
    DataViewProtoGetUint16,
    DataViewProtoGetInt8,
    DataViewProtoGetUint8,
    DataViewProtoSetFloat64,
    DataViewProtoSetFloat32,
    DataViewProtoSetInt32,
    DataViewProtoSetUint32,
    DataViewProtoSetInt16,
    DataViewProtoSetUint16,
    DataViewProtoSetInt8,
    DataViewProtoSetUint8,
    // ── TypedArray constructors ────────────────────────────────────────
    Int8ArrayConstructor,
    Uint8ArrayConstructor,
    Uint8ClampedArrayConstructor,
    Int16ArrayConstructor,
    Uint16ArrayConstructor,
    Int32ArrayConstructor,
    Uint32ArrayConstructor,
    Float32ArrayConstructor,
    Float64ArrayConstructor,
    // ── TypedArray prototype methods ───────────────────────────────────
    TypedArrayProtoLength,
    TypedArrayProtoByteLength,
    TypedArrayProtoByteOffset,
    TypedArrayProtoSet,
    TypedArrayProtoSlice,
    TypedArrayProtoSubarray,
    // ── TypedArray 新增构造器 ──
    BigInt64ArrayConstructor,
    BigUint64ArrayConstructor,
    // ── TypedArray 新增原型方法 — 简单方法 ──
    TypedArrayProtoFill,
    TypedArrayProtoReverse,
    TypedArrayProtoIndexOf,
    TypedArrayProtoLastIndexOf,
    TypedArrayProtoIncludes,
    TypedArrayProtoJoin,
    TypedArrayProtoToString,
    TypedArrayProtoCopyWithin,
    TypedArrayProtoAt,
    // ── TypedArray 新增原型方法 — 回调方法 (Type 12) ──
    TypedArrayProtoForEach,
    TypedArrayProtoMap,
    TypedArrayProtoFilter,
    TypedArrayProtoReduce,
    TypedArrayProtoReduceRight,
    TypedArrayProtoFind,
    TypedArrayProtoFindIndex,
    TypedArrayProtoSome,
    TypedArrayProtoEvery,
    TypedArrayProtoSort,
    // ── TypedArray 迭代器方法 ──
    TypedArrayProtoEntries,
    TypedArrayProtoKeys,
    TypedArrayProtoValues,
    GetBuiltinGlobal,
    CreateGlobalObject,
    CreateException,
    ExceptionValue,
    // ── Eval exception check ──
    IsException,
    // ── new.target meta property ──
    NewTarget,
    // ── Arguments Exotic Object ──
    CreateUnmappedArgumentsObject,
    CreateMappedArgumentsObject,
    // ── ScopeRecord eval bridge ───────────────────────────────────────
    /// dest: i64 — scope record handle
    ScopeRecordCreate,
    /// args[0]: record, args[1]: name (string), args[2]: value (i64), args[3]: is_tdz (bool), args[4]: is_const (bool)
    ScopeRecordAddBinding,
    /// dest: i64 — value (or TAG_EXCEPTION if TDZ)
    EvalGetBinding,
    /// dest: i64 — written value
    EvalSetBinding,
    /// dest: i64 — bool (0 or 1)
    EvalHasBinding,
    /// dest: i64 — prototype | undefined | TAG_EXCEPTION
    EvalSuperBase,
    /// args[0]: record, args[1]: key (i64 integer tag), args[2]: value (i64)
    ScopeRecordSetMeta,
    /// args[0]: record — removes the scope record from the runtime map
    ScopeRecordDestroy,
}

impl fmt::Display for Builtin {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::ConsoleLog => "console.log",
            Self::ConsoleError => "console.error",
            Self::ConsoleWarn => "console.warn",
            Self::ConsoleInfo => "console.info",
            Self::ConsoleDebug => "console.debug",
            Self::ConsoleTrace => "console.trace",
            Self::Debugger => "debugger",
            Self::Throw => "throw",
            Self::AbortShadowStackOverflow => "abort_shadow_stack_overflow",
            Self::F64Mod => "f64.mod",
            Self::F64Exp => "f64.exp",
            Self::IteratorFrom => "iterator.from",
            Self::IteratorNext => "iterator.next",
            Self::IteratorClose => "iterator.close",
            Self::AsyncIteratorFrom => "async_iterator.from",
            Self::IteratorValue => "iterator.value",
            Self::IteratorDone => "iterator.done",
            Self::EnumeratorFrom => "enumerator.from",
            Self::EnumeratorNext => "enumerator.next",
            Self::EnumeratorKey => "enumerator.key",
            Self::EnumeratorDone => "enumerator.done",
            Self::TypeOf => "typeof",
            Self::In => "op_in",
            Self::InstanceOf => "op_instanceof",
            Self::AbstractEq => "abstract_eq",
            Self::AbstractCompare => "abstract_compare",
            Self::DefineProperty => "define_property",
            Self::GetOwnPropDesc => "get_own_prop_desc",
            Self::SetTimeout => "setTimeout",
            Self::ClearTimeout => "clearTimeout",
            Self::SetInterval => "setInterval",
            Self::ClearInterval => "clearInterval",
            Self::Fetch => "fetch",
            Self::Eval => "eval",
            Self::EvalIndirect => "eval.indirect",
            Self::EvalResult => "eval.result",
            Self::JsonStringify => "JSON.stringify",
            Self::JsonParse => "JSON.parse",
            Self::CreateClosure => "create_closure",
            Self::ArrayPush => "array.push",
            Self::ArrayPop => "array.pop",
            Self::ArrayIncludes => "array.includes",
            Self::ArrayIndexOf => "array.index_of",
            Self::ArrayJoin => "array.join",
            Self::ArrayConcat => "array.concat",
            Self::ArraySlice => "array.slice",
            Self::ArrayFill => "array.fill",
            Self::ArrayReverse => "array.reverse",
            Self::ArrayFlat => "array.flat",
            Self::ArrayInitLength => "array.init_length",
            Self::ArrayGetLength => "array.get_length",
            Self::ArrayShift => "array.shift",
            Self::ArrayUnshiftVa => "array.unshift",
            Self::ArraySort => "array.sort",
            Self::ArrayAt => "array.at",
            Self::ArrayCopyWithin => "array.copy_within",
            Self::ArrayForEach => "array.for_each",
            Self::ArrayMap => "array.map",
            Self::ArrayFilter => "array.filter",
            Self::ArrayReduce => "array.reduce",
            Self::ArrayReduceRight => "array.reduce_right",
            Self::ArrayFind => "array.find",
            Self::ArrayFindIndex => "array.find_index",
            Self::ArraySome => "array.some",
            Self::ArrayEvery => "array.every",
            Self::ArrayFlatMap => "array.flat_map",
            Self::ArrayIsArray => "array.is_array",
            Self::ArrayFrom => "array.from",
            Self::ArraySpliceVa => "array.splice_va",
            Self::ArrayConcatVa => "array.concat_va",
            Self::FuncCall => "func_call",
            Self::FuncApply => "func_apply",
            Self::FuncBind => "func_bind",
            Self::ObjectRest => "object_rest",
            Self::GetPrototypeFromConstructor => "get_prototype_from_constructor",
            Self::HasOwnProperty => "has_own_property",
            Self::PrivateGet => "private_get",
            Self::PrivateSet => "private_set",
            Self::PrivateHas => "private_has",
            Self::ObjectProtoToString => "object_proto_to_string",
            Self::ObjectProtoValueOf => "object_proto_value_of",
            Self::ObjectKeys => "object.keys",
            Self::ObjectValues => "object.values",
            Self::ObjectEntries => "object.entries",
            Self::ObjectAssign => "object.assign",
            Self::ObjectCreate => "object.create",
            Self::ObjectGetPrototypeOf => "object.get_prototype_of",
            Self::ObjectSetPrototypeOf => "object.set_prototype_of",
            Self::ObjectGetOwnPropertyNames => "object.get_own_property_names",
            Self::ObjectIs => "object.is",
            Self::ObjectGroupBy => "object.group_by",
            Self::MapGroupBy => "map.group_by",
            Self::BigIntFromLiteral => "bigint.from_literal",
            Self::BigIntAdd => "bigint.add",
            Self::BigIntSub => "bigint.sub",
            Self::BigIntMul => "bigint.mul",
            Self::BigIntDiv => "bigint.div",
            Self::BigIntMod => "bigint.mod",
            Self::BigIntPow => "bigint.pow",
            Self::BigIntNeg => "bigint.neg",
            Self::BigIntEq => "bigint.eq",
            Self::BigIntCmp => "bigint.cmp",
            Self::SymbolCreate => "symbol.create",
            Self::SymbolFor => "symbol.for",
            Self::SymbolKeyFor => "symbol.key_for",
            Self::SymbolWellKnown => "symbol.well_known",
            Self::RegExpCreate => "regexp.create",
            Self::RegExpTest => "regexp.test",
            Self::RegExpExec => "regexp.exec",
            Self::StringMatch => "string.match",
            Self::StringReplace => "string.replace",
            Self::StringSearch => "string.search",
            Self::StringSplit => "string.split",
            Self::PromiseCreate => "promise.create",
            Self::PromiseInstanceResolve => "promise.instance_resolve",
            Self::PromiseInstanceReject => "promise.instance_reject",
            Self::PromiseCreateResolveFunction => "promise.create_resolve_function",
            Self::PromiseCreateRejectFunction => "promise.create_reject_function",
            Self::PromiseThen => "promise.then",
            Self::PromiseCatch => "promise.catch",
            Self::PromiseFinally => "promise.finally",
            Self::PromiseAll => "promise.all",
            Self::PromiseRace => "promise.race",
            Self::PromiseAllSettled => "promise.all_settled",
            Self::PromiseAny => "promise.any",
            Self::PromiseResolveStatic => "promise.resolve_static",
            Self::PromiseRejectStatic => "promise.reject_static",
            Self::IsPromise => "is_promise",
            Self::QueueMicrotask => "queue_microtask",
            Self::DrainMicrotasks => "drain_microtasks",
            Self::AsyncFunctionStart => "async_function.start",
            Self::AsyncFunctionResume => "async_function.resume",
            Self::AsyncFunctionSuspend => "async_function.suspend",
            Self::ContinuationCreate => "continuation.create",
            Self::ContinuationSaveVar => "continuation.save_var",
            Self::ContinuationLoadVar => "continuation.load_var",
            Self::AsyncGeneratorStart => "async_generator.start",
            Self::AsyncGeneratorNext => "async_generator.next",
            Self::AsyncGeneratorReturn => "async_generator.return",
            Self::PromiseWithResolvers => "promise.with_resolvers",
            Self::IsCallable => "is_callable",
            Self::AsyncGeneratorThrow => "async_generator.throw",
            Self::DynamicImport => "dynamic_import",
            Self::RegisterModuleNamespace => "register_module_namespace",
            Self::JsxCreateElement => "jsx.create_element",
            Self::ProxyCreate => "proxy.create",
            Self::ProxyRevocable => "proxy.revocable",
            Self::ReflectGet => "reflect.get",
            Self::ReflectSet => "reflect.set",
            Self::ReflectHas => "reflect.has",
            Self::ReflectDeleteProperty => "reflect.delete_property",
            Self::ReflectApply => "reflect.apply",
            Self::ReflectConstruct => "reflect.construct",
            Self::ReflectGetPrototypeOf => "reflect.get_prototype_of",
            Self::ReflectSetPrototypeOf => "reflect.set_prototype_of",
            Self::ReflectIsExtensible => "reflect.is_extensible",
            Self::ReflectPreventExtensions => "reflect.prevent_extensions",
            Self::ReflectGetOwnPropertyDescriptor => "reflect.get_own_property_descriptor",
            Self::ReflectDefineProperty => "reflect.define_property",
            Self::ReflectOwnKeys => "reflect.own_keys",
            Self::StringAt => "string.at",
            Self::StringCharAt => "string.char_at",
            Self::StringCharCodeAt => "string.char_code_at",
            Self::StringCodePointAt => "string.code_point_at",
            Self::StringConcatVa => "string.concat_va",
            Self::StringEndsWith => "string.ends_with",
            Self::StringIncludes => "string.includes",
            Self::StringIndexOf => "string.index_of",
            Self::StringLastIndexOf => "string.last_index_of",
            Self::StringMatchAll => "string.match_all",
            Self::StringPadEnd => "string.pad_end",
            Self::StringPadStart => "string.pad_start",
            Self::StringRepeat => "string.repeat",
            Self::StringReplaceAll => "string.replace_all",
            Self::StringSlice => "string.slice",
            Self::StringStartsWith => "string.starts_with",
            Self::StringSubstring => "string.substring",
            Self::StringToLowerCase => "string.to_lower_case",
            Self::StringToUpperCase => "string.to_upper_case",
            Self::StringTrim => "string.trim",
            Self::StringTrimEnd => "string.trim_end",
            Self::StringTrimStart => "string.trim_start",
            Self::StringToString => "string.to_string",
            Self::StringValueOf => "string.value_of",
            Self::StringIterator => "string.iterator",
            Self::StringFromCharCode => "string.from_char_code",
            Self::StringFromCodePoint => "string.from_code_point",
            Self::MathAbs => "Math.abs",
            Self::MathAcos => "Math.acos",
            Self::MathAcosh => "Math.acosh",
            Self::MathAsin => "Math.asin",
            Self::MathAsinh => "Math.asinh",
            Self::MathAtan => "Math.atan",
            Self::MathAtanh => "Math.atanh",
            Self::MathAtan2 => "Math.atan2",
            Self::MathCbrt => "Math.cbrt",
            Self::MathCeil => "Math.ceil",
            Self::MathClz32 => "Math.clz32",
            Self::MathCos => "Math.cos",
            Self::MathCosh => "Math.cosh",
            Self::MathExp => "Math.exp",
            Self::MathExpm1 => "Math.expm1",
            Self::MathFloor => "Math.floor",
            Self::MathFround => "Math.fround",
            Self::MathHypot => "Math.hypot",
            Self::MathImul => "Math.imul",
            Self::MathLog => "Math.log",
            Self::MathLog1p => "Math.log1p",
            Self::MathLog10 => "Math.log10",
            Self::MathLog2 => "Math.log2",
            Self::MathMax => "Math.max",
            Self::MathMin => "Math.min",
            Self::MathPow => "Math.pow",
            Self::MathRandom => "Math.random",
            Self::MathRound => "Math.round",
            Self::MathSign => "Math.sign",
            Self::MathSin => "Math.sin",
            Self::MathSinh => "Math.sinh",
            Self::MathSqrt => "Math.sqrt",
            Self::MathTan => "Math.tan",
            Self::MathTanh => "Math.tanh",
            Self::MathTrunc => "Math.trunc",
            Self::NumberConstructor => "Number",
            Self::NumberIsNaN => "Number.isNaN",
            Self::NumberIsFinite => "Number.isFinite",
            Self::NumberIsInteger => "Number.isInteger",
            Self::NumberIsSafeInteger => "Number.isSafeInteger",
            Self::NumberParseInt => "Number.parseInt",
            Self::NumberParseFloat => "Number.parseFloat",
            Self::NumberProtoToString => "Number.prototype.toString",
            Self::NumberProtoValueOf => "Number.prototype.valueOf",
            Self::NumberProtoToFixed => "Number.prototype.toFixed",
            Self::NumberProtoToExponential => "Number.prototype.toExponential",
            Self::NumberProtoToPrecision => "Number.prototype.toPrecision",
            Self::BooleanConstructor => "Boolean",
            Self::BooleanProtoToString => "Boolean.prototype.toString",
            Self::BooleanProtoValueOf => "Boolean.prototype.valueOf",
            Self::ErrorConstructor => "Error",
            Self::TypeErrorConstructor => "TypeError",
            Self::RangeErrorConstructor => "RangeError",
            Self::SyntaxErrorConstructor => "SyntaxError",
            Self::ReferenceErrorConstructor => "ReferenceError",
            Self::URIErrorConstructor => "URIError",
            Self::EvalErrorConstructor => "EvalError",
            Self::ErrorProtoToString => "Error.prototype.toString",
            Self::MapConstructor => "Map",
            Self::MapProtoSet => "Map.prototype.set",
            Self::MapProtoGet => "Map.prototype.get",
            Self::SetConstructor => "Set",
            Self::SetProtoAdd => "Set.prototype.add",
            Self::MapSetHas => "MapSet.has",
            Self::MapSetDelete => "MapSet.delete",
            Self::MapSetClear => "MapSet.clear",
            Self::MapSetGetSize => "MapSet.size",
            Self::MapSetForEach => "MapSet.forEach",
            Self::MapSetKeys => "MapSet.keys",
            Self::MapSetValues => "MapSet.values",
            Self::MapSetEntries => "MapSet.entries",
            Self::DateConstructor => "Date",
            Self::DateNow => "Date.now",
            Self::DateParse => "Date.parse",
            Self::DateUTC => "Date.UTC",
            Self::WeakMapConstructor => "WeakMap",
            Self::WeakMapProtoSet => "WeakMap.prototype.set",
            Self::WeakMapProtoGet => "WeakMap.prototype.get",
            Self::WeakMapProtoHas => "WeakMap.prototype.has",
            Self::WeakMapProtoDelete => "WeakMap.prototype.delete",
            Self::WeakSetConstructor => "WeakSet",
            Self::WeakSetProtoAdd => "WeakSet.prototype.add",
            Self::WeakSetProtoHas => "WeakSet.prototype.has",
            Self::WeakSetProtoDelete => "WeakSet.prototype.delete",
            Self::SharedArrayBufferConstructor => "SharedArrayBuffer",
            Self::SharedArrayBufferProtoByteLength => "SharedArrayBuffer.prototype.byteLength",
            Self::SharedArrayBufferProtoSlice => "SharedArrayBuffer.prototype.slice",
            Self::SharedArrayBufferSpecies => "SharedArrayBuffer[Symbol.species]",
            Self::AtomicsLoad => "Atomics.load",
            Self::AtomicsStore => "Atomics.store",
            Self::AtomicsAdd => "Atomics.add",
            Self::AtomicsSub => "Atomics.sub",
            Self::AtomicsAnd => "Atomics.and",
            Self::AtomicsOr => "Atomics.or",
            Self::AtomicsXor => "Atomics.xor",
            Self::AtomicsExchange => "Atomics.exchange",
            Self::AtomicsCompareExchange => "Atomics.compareExchange",
            Self::AtomicsIsLockFree => "Atomics.isLockFree",
            Self::AtomicsWait => "Atomics.wait",
            Self::AtomicsNotify => "Atomics.notify",
            Self::AtomicsWaitAsync => "Atomics.waitAsync",
            Self::WeakRefConstructor => "WeakRef",
            Self::WeakRefProtoDeref => "WeakRef.prototype.deref",
            Self::FinalizationRegistryConstructor => "FinalizationRegistry",
            Self::FinalizationRegistryProtoRegister => "FinalizationRegistry.prototype.register",
            Self::FinalizationRegistryProtoUnregister => "FinalizationRegistry.prototype.unregister",
            Self::ArrayBufferConstructor => "ArrayBuffer",
            Self::ArrayBufferProtoByteLength => "ArrayBuffer.prototype.byteLength",
            Self::ArrayBufferProtoSlice => "ArrayBuffer.prototype.slice",
            Self::DataViewConstructor => "DataView",
            Self::DataViewProtoGetFloat64 => "DataView.prototype.getFloat64",
            Self::DataViewProtoGetFloat32 => "DataView.prototype.getFloat32",
            Self::DataViewProtoGetInt32 => "DataView.prototype.getInt32",
            Self::DataViewProtoGetUint32 => "DataView.prototype.getUint32",
            Self::DataViewProtoGetInt16 => "DataView.prototype.getInt16",
            Self::DataViewProtoGetUint16 => "DataView.prototype.getUint16",
            Self::DataViewProtoGetInt8 => "DataView.prototype.getInt8",
            Self::DataViewProtoGetUint8 => "DataView.prototype.getUint8",
            Self::DataViewProtoSetFloat64 => "DataView.prototype.setFloat64",
            Self::DataViewProtoSetFloat32 => "DataView.prototype.setFloat32",
            Self::DataViewProtoSetInt32 => "DataView.prototype.setInt32",
            Self::DataViewProtoSetUint32 => "DataView.prototype.setUint32",
            Self::DataViewProtoSetInt16 => "DataView.prototype.setInt16",
            Self::DataViewProtoSetUint16 => "DataView.prototype.setUint16",
            Self::DataViewProtoSetInt8 => "DataView.prototype.setInt8",
            Self::DataViewProtoSetUint8 => "DataView.prototype.setUint8",
            Self::Int8ArrayConstructor => "Int8Array",
            Self::Uint8ArrayConstructor => "Uint8Array",
            Self::Uint8ClampedArrayConstructor => "Uint8ClampedArray",
            Self::Int16ArrayConstructor => "Int16Array",
            Self::Uint16ArrayConstructor => "Uint16Array",
            Self::Int32ArrayConstructor => "Int32Array",
            Self::Uint32ArrayConstructor => "Uint32Array",
            Self::Float32ArrayConstructor => "Float32Array",
            Self::Float64ArrayConstructor => "Float64Array",
            Self::TypedArrayProtoLength => "TypedArray.prototype.length",
            Self::TypedArrayProtoByteLength => "TypedArray.prototype.byteLength",
            Self::TypedArrayProtoByteOffset => "TypedArray.prototype.byteOffset",
            Self::TypedArrayProtoSet => "TypedArray.prototype.set",
            Self::TypedArrayProtoSlice => "TypedArray.prototype.slice",
            Self::TypedArrayProtoSubarray => "TypedArray.prototype.subarray",
            Self::BigInt64ArrayConstructor => "BigInt64Array",
            Self::BigUint64ArrayConstructor => "BigUint64Array",
            Self::TypedArrayProtoFill => "TypedArray.prototype.fill",
            Self::TypedArrayProtoReverse => "TypedArray.prototype.reverse",
            Self::TypedArrayProtoIndexOf => "TypedArray.prototype.indexOf",
            Self::TypedArrayProtoLastIndexOf => "TypedArray.prototype.lastIndexOf",
            Self::TypedArrayProtoIncludes => "TypedArray.prototype.includes",
            Self::TypedArrayProtoJoin => "TypedArray.prototype.join",
            Self::TypedArrayProtoToString => "TypedArray.prototype.toString",
            Self::TypedArrayProtoCopyWithin => "TypedArray.prototype.copyWithin",
            Self::TypedArrayProtoAt => "TypedArray.prototype.at",
            Self::TypedArrayProtoForEach => "TypedArray.prototype.forEach",
            Self::TypedArrayProtoMap => "TypedArray.prototype.map",
            Self::TypedArrayProtoFilter => "TypedArray.prototype.filter",
            Self::TypedArrayProtoReduce => "TypedArray.prototype.reduce",
            Self::TypedArrayProtoReduceRight => "TypedArray.prototype.reduceRight",
            Self::TypedArrayProtoFind => "TypedArray.prototype.find",
            Self::TypedArrayProtoFindIndex => "TypedArray.prototype.findIndex",
            Self::TypedArrayProtoSome => "TypedArray.prototype.some",
            Self::TypedArrayProtoEvery => "TypedArray.prototype.every",
            Self::TypedArrayProtoSort => "TypedArray.prototype.sort",
            Self::TypedArrayProtoEntries => "TypedArray.prototype.entries",
            Self::TypedArrayProtoKeys => "TypedArray.prototype.keys",
            Self::TypedArrayProtoValues => "TypedArray.prototype.values",
            Self::GetBuiltinGlobal => "get_builtin_global",
            Self::CreateGlobalObject => "create_global_object",
            Self::CreateException => "create_exception",
            Self::ExceptionValue => "exception_value",
            Self::IsException => "is_exception",
            Self::NewTarget => "new.target",
            Self::CreateUnmappedArgumentsObject => "create_unmapped_arguments_object",
            Self::CreateMappedArgumentsObject => "create_mapped_arguments_object",
            Self::ScopeRecordCreate => "scope_record_create",
            Self::ScopeRecordAddBinding => "scope_record_add_binding",
            Self::EvalGetBinding => "eval_get_binding",
            Self::EvalSetBinding => "eval_set_binding",
            Self::EvalHasBinding => "eval_has_binding",
            Self::EvalSuperBase => "eval_super_base",
            Self::ScopeRecordSetMeta => "scope_record_set_meta",
            Self::ScopeRecordDestroy => "scope_record_destroy",
        })
    }
}

impl Builtin {
    /// 返回 WASM import section / HOST_IMPORT_NAMES 中对应的名字。
    pub fn import_name(self) -> &'static str {
        match self {
            Self::ConsoleLog => "console_log",
            Self::ConsoleError => "console_error",
            Self::ConsoleWarn => "console_warn",
            Self::ConsoleInfo => "console_info",
            Self::ConsoleDebug => "console_debug",
            Self::ConsoleTrace => "console_trace",
            Self::Debugger => "debugger",
            Self::Throw => "throw",
            Self::AbortShadowStackOverflow => "abort_shadow_stack_overflow",
            Self::F64Mod => "f64_mod",
            Self::F64Exp => "f64_pow",
            Self::IteratorFrom => "iterator_from",
            Self::IteratorNext => "iterator_next",
            Self::IteratorClose => "iterator_close",
            Self::AsyncIteratorFrom => "async_iterator_from",
            Self::IteratorValue => "iterator_value",
            Self::IteratorDone => "iterator_done",
            Self::EnumeratorFrom => "enumerator_from",
            Self::EnumeratorNext => "enumerator_next",
            Self::EnumeratorKey => "enumerator_key",
            Self::EnumeratorDone => "enumerator_done",
            Self::TypeOf => "typeof",
            Self::In => "op_in",
            Self::InstanceOf => "op_instanceof",
            Self::AbstractEq => "abstract_eq",
            Self::AbstractCompare => "abstract_compare",
            Self::DefineProperty => "define_property",
            Self::GetOwnPropDesc => "get_own_prop_desc",
            Self::SetTimeout => "set_timeout",
            Self::ClearTimeout => "clear_timeout",
            Self::SetInterval => "set_interval",
            Self::ClearInterval => "clear_interval",
            Self::Fetch => "fetch",
            Self::Eval => "eval_direct",
            Self::EvalIndirect => "eval_indirect",
            Self::EvalResult => "eval_result",
            Self::JsonStringify => "json_stringify",
            Self::JsonParse => "json_parse",
            Self::CreateClosure => "closure_create",
            Self::ArrayPush => "arr_push",
            Self::ArrayPop => "arr_pop",
            Self::ArrayIncludes => "arr_includes",
            Self::ArrayIndexOf => "arr_index_of",
            Self::ArrayJoin => "arr_join",
            Self::ArrayConcat => "arr_concat",
            Self::ArraySlice => "arr_slice",
            Self::ArrayFill => "arr_fill",
            Self::ArrayReverse => "arr_reverse",
            Self::ArrayFlat => "arr_flat",
            Self::ArrayInitLength => "arr_init_length",
            Self::ArrayGetLength => "arr_get_length",
            Self::ArrayShift => "arr_proto_shift",
            Self::ArrayUnshiftVa => "arr_proto_unshift",
            Self::ArraySort => "arr_proto_sort",
            Self::ArrayAt => "arr_proto_at",
            Self::ArrayCopyWithin => "arr_proto_copy_within",
            Self::ArrayForEach => "arr_proto_for_each",
            Self::ArrayMap => "arr_proto_map",
            Self::ArrayFilter => "arr_proto_filter",
            Self::ArrayReduce => "arr_proto_reduce",
            Self::ArrayReduceRight => "arr_proto_reduce_right",
            Self::ArrayFind => "arr_proto_find",
            Self::ArrayFindIndex => "arr_proto_find_index",
            Self::ArraySome => "arr_proto_some",
            Self::ArrayEvery => "arr_proto_every",
            Self::ArrayFlatMap => "arr_proto_flat_map",
            Self::ArrayIsArray => "arr_proto_is_array",
            Self::ArrayFrom => "array.from",
            Self::ArraySpliceVa => "arr_proto_splice",
            Self::ArrayConcatVa => "string_concat_va",
            Self::FuncCall => "func_call",
            Self::FuncApply => "func_apply",
            Self::FuncBind => "func_bind",
            Self::ObjectRest => "object_rest",
            Self::GetPrototypeFromConstructor => "get_prototype_from_constructor",
            Self::HasOwnProperty => "has_own_property",
            Self::PrivateGet => "private_get",
            Self::PrivateSet => "private_set",
            Self::PrivateHas => "private_has",
            Self::ObjectProtoToString => "obj_proto_to_string",
            Self::ObjectProtoValueOf => "obj_proto_value_of",
            Self::ObjectKeys => "obj_keys",
            Self::ObjectValues => "obj_values",
            Self::ObjectEntries => "obj_entries",
            Self::ObjectAssign => "obj_assign",
            Self::ObjectCreate => "obj_create",
            Self::ObjectGetPrototypeOf => "obj_get_proto_of",
            Self::ObjectSetPrototypeOf => "obj_set_proto_of",
            Self::ObjectGetOwnPropertyNames => "obj_get_own_prop_names",
            Self::ObjectIs => "obj_is",
            Self::ObjectGroupBy => "object.group_by",
            Self::MapGroupBy => "map.group_by",
            Self::BigIntFromLiteral => "bigint_from_literal",
            Self::BigIntAdd => "bigint_add",
            Self::BigIntSub => "bigint_sub",
            Self::BigIntMul => "bigint_mul",
            Self::BigIntDiv => "bigint_div",
            Self::BigIntMod => "bigint_mod",
            Self::BigIntPow => "bigint_pow",
            Self::BigIntNeg => "bigint_neg",
            Self::BigIntEq => "bigint_eq",
            Self::BigIntCmp => "bigint_cmp",
            Self::SymbolCreate => "symbol_create",
            Self::SymbolFor => "symbol_for",
            Self::SymbolKeyFor => "symbol_key_for",
            Self::SymbolWellKnown => "symbol_well_known",
            Self::RegExpCreate => "regex_create",
            Self::RegExpTest => "regex_test",
            Self::RegExpExec => "regex_exec",
            Self::StringMatch => "string_match",
            Self::StringReplace => "string_replace",
            Self::StringSearch => "string_search",
            Self::StringSplit => "string_split",
            Self::PromiseCreate => "promise_create",
            Self::PromiseInstanceResolve => "promise_instance_resolve",
            Self::PromiseInstanceReject => "promise_instance_reject",
            Self::PromiseCreateResolveFunction => "promise_create_resolve_function",
            Self::PromiseCreateRejectFunction => "promise_create_reject_function",
            Self::PromiseThen => "promise_then",
            Self::PromiseCatch => "promise_catch",
            Self::PromiseFinally => "promise_finally",
            Self::PromiseAll => "promise_all",
            Self::PromiseRace => "promise_race",
            Self::PromiseAllSettled => "promise_all_settled",
            Self::PromiseAny => "promise_any",
            Self::PromiseResolveStatic => "promise_resolve_static",
            Self::PromiseRejectStatic => "promise_reject_static",
            Self::IsPromise => "is_promise",
            Self::QueueMicrotask => "queue_microtask",
            Self::DrainMicrotasks => "drain_microtasks",
            Self::AsyncFunctionStart => "async_function_start",
            Self::AsyncFunctionResume => "async_function_resume",
            Self::AsyncFunctionSuspend => "async_function_suspend",
            Self::ContinuationCreate => "continuation_create",
            Self::ContinuationSaveVar => "continuation_save_var",
            Self::ContinuationLoadVar => "continuation_load_var",
            Self::AsyncGeneratorStart => "async_generator_start",
            Self::AsyncGeneratorNext => "async_generator_next",
            Self::AsyncGeneratorReturn => "async_generator_return",
            Self::AsyncGeneratorThrow => "async_generator_throw",
            Self::PromiseWithResolvers => "promise_with_resolvers",
            Self::IsCallable => "is_callable",
            Self::DynamicImport => "dynamic_import",
            Self::RegisterModuleNamespace => "register_module_namespace",
            Self::JsxCreateElement => "jsx_create_element",
            Self::ProxyCreate => "proxy_create",
            Self::ProxyRevocable => "proxy_revocable",
            Self::ReflectGet => "reflect_get",
            Self::ReflectSet => "reflect_set",
            Self::ReflectHas => "reflect_has",
            Self::ReflectDeleteProperty => "reflect_delete_property",
            Self::ReflectApply => "reflect_apply",
            Self::ReflectConstruct => "reflect_construct",
            Self::ReflectGetPrototypeOf => "reflect_get_prototype_of",
            Self::ReflectSetPrototypeOf => "reflect_set_prototype_of",
            Self::ReflectIsExtensible => "reflect_is_extensible",
            Self::ReflectPreventExtensions => "reflect_prevent_extensions",
            Self::ReflectGetOwnPropertyDescriptor => "reflect_get_own_property_descriptor",
            Self::ReflectDefineProperty => "reflect_define_property",
            Self::ReflectOwnKeys => "reflect_own_keys",
            Self::StringAt => "string_at",
            Self::StringCharAt => "string_char_at",
            Self::StringCharCodeAt => "string_char_code_at",
            Self::StringCodePointAt => "string_code_point_at",
            Self::StringConcatVa => "string_concat_proto",
            Self::StringEndsWith => "string_ends_with",
            Self::StringIncludes => "string_includes",
            Self::StringIndexOf => "string_index_of",
            Self::StringLastIndexOf => "string_last_index_of",
            Self::StringMatchAll => "string_match_all",
            Self::StringPadEnd => "string_pad_end",
            Self::StringPadStart => "string_pad_start",
            Self::StringRepeat => "string_repeat",
            Self::StringReplaceAll => "string_replace_all",
            Self::StringSlice => "string_slice",
            Self::StringStartsWith => "string_starts_with",
            Self::StringSubstring => "string_substring",
            Self::StringToLowerCase => "string_to_lower_case",
            Self::StringToUpperCase => "string_to_upper_case",
            Self::StringTrim => "string_trim",
            Self::StringTrimEnd => "string_trim_end",
            Self::StringTrimStart => "string_trim_start",
            Self::StringToString => "string_to_string",
            Self::StringValueOf => "string_value_of",
            Self::StringIterator => "string_iterator",
            Self::StringFromCharCode => "string_from_char_code",
            Self::StringFromCodePoint => "string_from_code_point",
            Self::MathAbs => "math_abs",
            Self::MathAcos => "math_acos",
            Self::MathAcosh => "math_acosh",
            Self::MathAsin => "math_asin",
            Self::MathAsinh => "math_asinh",
            Self::MathAtan => "math_atan",
            Self::MathAtanh => "math_atanh",
            Self::MathAtan2 => "math_atan2",
            Self::MathCbrt => "math_cbrt",
            Self::MathCeil => "math_ceil",
            Self::MathClz32 => "math_clz32",
            Self::MathCos => "math_cos",
            Self::MathCosh => "math_cosh",
            Self::MathExp => "math_exp",
            Self::MathExpm1 => "math_expm1",
            Self::MathFloor => "math_floor",
            Self::MathFround => "math_fround",
            Self::MathHypot => "math_hypot",
            Self::MathImul => "math_imul",
            Self::MathLog => "math_log",
            Self::MathLog1p => "math_log1p",
            Self::MathLog10 => "math_log10",
            Self::MathLog2 => "math_log2",
            Self::MathMax => "math_max",
            Self::MathMin => "math_min",
            Self::MathPow => "math_pow",
            Self::MathRandom => "math_random",
            Self::MathRound => "math_round",
            Self::MathSign => "math_sign",
            Self::MathSin => "math_sin",
            Self::MathSinh => "math_sinh",
            Self::MathSqrt => "math_sqrt",
            Self::MathTan => "math_tan",
            Self::MathTanh => "math_tanh",
            Self::MathTrunc => "math_trunc",
            Self::NumberConstructor => "number_constructor",
            Self::NumberIsNaN => "number_is_nan",
            Self::NumberIsFinite => "number_is_finite",
            Self::NumberIsInteger => "number_is_integer",
            Self::NumberIsSafeInteger => "number_is_safe_integer",
            Self::NumberParseInt => "number_parse_int",
            Self::NumberParseFloat => "number_parse_float",
            Self::NumberProtoToString => "number_proto_to_string",
            Self::NumberProtoValueOf => "number_proto_value_of",
            Self::NumberProtoToFixed => "number_proto_to_fixed",
            Self::NumberProtoToExponential => "number_proto_to_exponential",
            Self::NumberProtoToPrecision => "number_proto_to_precision",
            Self::BooleanConstructor => "boolean_constructor",
            Self::BooleanProtoToString => "boolean_proto_to_string",
            Self::BooleanProtoValueOf => "boolean_proto_value_of",
            Self::ErrorConstructor => "error_constructor",
            Self::TypeErrorConstructor => "type_error_constructor",
            Self::RangeErrorConstructor => "range_error_constructor",
            Self::SyntaxErrorConstructor => "syntax_error_constructor",
            Self::ReferenceErrorConstructor => "reference_error_constructor",
            Self::URIErrorConstructor => "uri_error_constructor",
            Self::EvalErrorConstructor => "eval_error_constructor",
            Self::ErrorProtoToString => "error_proto_to_string",
            Self::MapConstructor => "map_constructor",
            Self::MapProtoSet => "map_proto_set",
            Self::MapProtoGet => "map_proto_get",
            Self::SetConstructor => "set_constructor",
            Self::SetProtoAdd => "set_proto_add",
            Self::MapSetHas => "map_set_has",
            Self::MapSetDelete => "map_set_delete",
            Self::MapSetClear => "map_set_clear",
            Self::MapSetGetSize => "map_set_get_size",
            Self::MapSetForEach => "map_set_for_each",
            Self::MapSetKeys => "map_set_keys",
            Self::MapSetValues => "map_set_values",
            Self::MapSetEntries => "map_set_entries",
            Self::DateConstructor => "date_constructor",
            Self::DateNow => "date_now",
            Self::DateParse => "date_parse",
            Self::DateUTC => "date_utc",
            Self::WeakMapConstructor => "weakmap_constructor",
            Self::WeakMapProtoSet => "weakmap_proto_set",
            Self::WeakMapProtoGet => "weakmap_proto_get",
            Self::WeakMapProtoHas => "weakmap_proto_has",
            Self::WeakMapProtoDelete => "weakmap_proto_delete",
            Self::WeakSetConstructor => "weakset_constructor",
            Self::WeakSetProtoAdd => "weakset_proto_add",
            Self::WeakSetProtoHas => "weakset_proto_has",
            Self::WeakSetProtoDelete => "weakset_proto_delete",
            Self::SharedArrayBufferConstructor => "sharedarraybuffer_constructor",
            Self::SharedArrayBufferProtoByteLength => "sharedarraybuffer_proto_byte_length",
            Self::SharedArrayBufferProtoSlice => "sharedarraybuffer_proto_slice",
            Self::SharedArrayBufferSpecies => "sharedarraybuffer_proto_species",
            Self::AtomicsLoad => "atomics_load",
            Self::AtomicsStore => "atomics_store",
            Self::AtomicsAdd => "atomics_add",
            Self::AtomicsSub => "atomics_sub",
            Self::AtomicsAnd => "atomics_and",
            Self::AtomicsOr => "atomics_or",
            Self::AtomicsXor => "atomics_xor",
            Self::AtomicsExchange => "atomics_exchange",
            Self::AtomicsCompareExchange => "atomics_compare_exchange",
            Self::AtomicsIsLockFree => "atomics_is_lock_free",
            Self::AtomicsWait => "atomics_wait",
            Self::AtomicsNotify => "atomics_notify",
            Self::AtomicsWaitAsync => "atomics_wait_async",
            Self::WeakRefConstructor => "weakref_constructor",
            Self::WeakRefProtoDeref => "weakref_proto_deref",
            Self::FinalizationRegistryConstructor => "finalization_registry_constructor",
            Self::FinalizationRegistryProtoRegister => "finalization_registry_proto_register",
            Self::FinalizationRegistryProtoUnregister => "finalization_registry_proto_unregister",
            Self::ArrayBufferConstructor => "arraybuffer_constructor",
            Self::ArrayBufferProtoByteLength => "arraybuffer_proto_byte_length",
            Self::ArrayBufferProtoSlice => "arraybuffer_proto_slice",
            Self::DataViewConstructor => "dataview_constructor",
            Self::DataViewProtoGetFloat64 => "dataview_proto_get_float64",
            Self::DataViewProtoGetFloat32 => "dataview_proto_get_float32",
            Self::DataViewProtoGetInt32 => "dataview_proto_get_int32",
            Self::DataViewProtoGetUint32 => "dataview_proto_get_uint32",
            Self::DataViewProtoGetInt16 => "dataview_proto_get_int16",
            Self::DataViewProtoGetUint16 => "dataview_proto_get_uint16",
            Self::DataViewProtoGetInt8 => "dataview_proto_get_int8",
            Self::DataViewProtoGetUint8 => "dataview_proto_get_uint8",
            Self::DataViewProtoSetFloat64 => "dataview_proto_set_float64",
            Self::DataViewProtoSetFloat32 => "dataview_proto_set_float32",
            Self::DataViewProtoSetInt32 => "dataview_proto_set_int32",
            Self::DataViewProtoSetUint32 => "dataview_proto_set_uint32",
            Self::DataViewProtoSetInt16 => "dataview_proto_set_int16",
            Self::DataViewProtoSetUint16 => "dataview_proto_set_uint16",
            Self::DataViewProtoSetInt8 => "dataview_proto_set_int8",
            Self::DataViewProtoSetUint8 => "dataview_proto_set_uint8",
            Self::Int8ArrayConstructor => "int8array_constructor",
            Self::Uint8ArrayConstructor => "uint8array_constructor",
            Self::Uint8ClampedArrayConstructor => "uint8clampedarray_constructor",
            Self::Int16ArrayConstructor => "int16array_constructor",
            Self::Uint16ArrayConstructor => "uint16array_constructor",
            Self::Int32ArrayConstructor => "int32array_constructor",
            Self::Uint32ArrayConstructor => "uint32array_constructor",
            Self::Float32ArrayConstructor => "float32array_constructor",
            Self::Float64ArrayConstructor => "float64array_constructor",
            Self::TypedArrayProtoLength => "typedarray_proto_length",
            Self::TypedArrayProtoByteLength => "typedarray_proto_byte_length",
            Self::TypedArrayProtoByteOffset => "typedarray_proto_byte_offset",
            Self::TypedArrayProtoSet => "typedarray_proto_set",
            Self::TypedArrayProtoSlice => "typedarray_proto_slice",
            Self::TypedArrayProtoSubarray => "typedarray_proto_subarray",
            Self::BigInt64ArrayConstructor => "bigint64array_constructor",
            Self::BigUint64ArrayConstructor => "biguint64array_constructor",
            Self::TypedArrayProtoFill => "typedarray_proto_fill",
            Self::TypedArrayProtoReverse => "typedarray_proto_reverse",
            Self::TypedArrayProtoIndexOf => "typedarray_proto_index_of",
            Self::TypedArrayProtoLastIndexOf => "typedarray_proto_last_index_of",
            Self::TypedArrayProtoIncludes => "typedarray_proto_includes",
            Self::TypedArrayProtoJoin => "typedarray_proto_join",
            Self::TypedArrayProtoToString => "typedarray_proto_to_string",
            Self::TypedArrayProtoCopyWithin => "typedarray_proto_copy_within",
            Self::TypedArrayProtoAt => "typedarray_proto_at",
            Self::TypedArrayProtoForEach => "typedarray_proto_for_each",
            Self::TypedArrayProtoMap => "typedarray_proto_map",
            Self::TypedArrayProtoFilter => "typedarray_proto_filter",
            Self::TypedArrayProtoReduce => "typedarray_proto_reduce",
            Self::TypedArrayProtoReduceRight => "typedarray_proto_reduce_right",
            Self::TypedArrayProtoFind => "typedarray_proto_find",
            Self::TypedArrayProtoFindIndex => "typedarray_proto_find_index",
            Self::TypedArrayProtoSome => "typedarray_proto_some",
            Self::TypedArrayProtoEvery => "typedarray_proto_every",
            Self::TypedArrayProtoSort => "typedarray_proto_sort",
            Self::TypedArrayProtoEntries => "typedarray_proto_entries",
            Self::TypedArrayProtoKeys => "typedarray_proto_keys",
            Self::TypedArrayProtoValues => "typedarray_proto_values",
            Self::GetBuiltinGlobal => "get_builtin_global",
            Self::CreateGlobalObject => "create_global_object",
            Self::CreateException => "create_exception",
            Self::ExceptionValue => "exception_value",
            Self::IsException => "is_exception",
            Self::NewTarget => "new_target",
            Self::CreateUnmappedArgumentsObject => "create_unmapped_arguments_object",
            Self::CreateMappedArgumentsObject => "create_mapped_arguments_object",
            Self::ScopeRecordCreate => "scope_record_create",
            Self::ScopeRecordAddBinding => "scope_record_add_binding",
            Self::EvalGetBinding => "eval_get_binding",
            Self::EvalSetBinding => "eval_set_binding",
            Self::EvalHasBinding => "eval_has_binding",
            Self::EvalSuperBase => "eval_super_base",
            Self::ScopeRecordSetMeta => "scope_record_set_meta",
            Self::ScopeRecordDestroy => "scope_record_destroy",
        }
    }
}

/// 所有 Builtin 变体的数组，用于自动生成 builtin_func_indices。
pub const ALL_BUILTINS: &[Builtin] = &[
    Builtin::ConsoleLog,
    Builtin::ConsoleError,
    Builtin::ConsoleWarn,
    Builtin::ConsoleInfo,
    Builtin::ConsoleDebug,
    Builtin::ConsoleTrace,
    Builtin::Debugger,
    Builtin::Throw,
    Builtin::AbortShadowStackOverflow,
    Builtin::F64Mod,
    Builtin::F64Exp,
    Builtin::IteratorFrom,
    Builtin::IteratorNext,
    Builtin::IteratorClose,
    Builtin::AsyncIteratorFrom,
    Builtin::IteratorValue,
    Builtin::IteratorDone,
    Builtin::EnumeratorFrom,
    Builtin::EnumeratorNext,
    Builtin::EnumeratorKey,
    Builtin::EnumeratorDone,
    Builtin::TypeOf,
    Builtin::In,
    Builtin::InstanceOf,
    Builtin::AbstractEq,
    Builtin::AbstractCompare,
    Builtin::DefineProperty,
    Builtin::GetOwnPropDesc,
    Builtin::SetTimeout,
    Builtin::ClearTimeout,
    Builtin::SetInterval,
    Builtin::ClearInterval,
    Builtin::Fetch,
    Builtin::Eval,
    Builtin::EvalIndirect,
    Builtin::JsonStringify,
    Builtin::JsonParse,
    Builtin::CreateClosure,
    Builtin::ArrayPush,
    Builtin::ArrayPop,
    Builtin::ArrayIncludes,
    Builtin::ArrayIndexOf,
    Builtin::ArrayJoin,
    Builtin::ArrayConcat,
    Builtin::ArraySlice,
    Builtin::ArrayFill,
    Builtin::ArrayReverse,
    Builtin::ArrayFlat,
    Builtin::ArrayInitLength,
    Builtin::ArrayGetLength,
    Builtin::ArrayShift,
    Builtin::ArrayUnshiftVa,
    Builtin::ArraySort,
    Builtin::ArrayAt,
    Builtin::ArrayCopyWithin,
    Builtin::ArrayForEach,
    Builtin::ArrayMap,
    Builtin::ArrayFilter,
    Builtin::ArrayReduce,
    Builtin::ArrayReduceRight,
    Builtin::ArrayFind,
    Builtin::ArrayFindIndex,
    Builtin::ArraySome,
    Builtin::ArrayEvery,
    Builtin::ArrayFlatMap,
    Builtin::ArrayIsArray,
    Builtin::ArrayFrom,
    Builtin::ArraySpliceVa,
    Builtin::ArrayConcatVa,
    Builtin::FuncCall,
    Builtin::FuncApply,
    Builtin::FuncBind,
    Builtin::ObjectRest,
    Builtin::HasOwnProperty,
    Builtin::PrivateGet,
    Builtin::PrivateSet,
    Builtin::PrivateHas,
    Builtin::ObjectProtoToString,
    Builtin::ObjectProtoValueOf,
    Builtin::ObjectKeys,
    Builtin::ObjectValues,
    Builtin::ObjectEntries,
    Builtin::ObjectAssign,
    Builtin::ObjectCreate,
    Builtin::ObjectGetPrototypeOf,
    Builtin::ObjectSetPrototypeOf,
    Builtin::ObjectGetOwnPropertyNames,
    Builtin::ObjectIs,
    Builtin::ObjectGroupBy,
    Builtin::MapGroupBy,
    Builtin::BigIntFromLiteral,
    Builtin::BigIntAdd,
    Builtin::BigIntSub,
    Builtin::BigIntMul,
    Builtin::BigIntDiv,
    Builtin::BigIntMod,
    Builtin::BigIntPow,
    Builtin::BigIntNeg,
    Builtin::BigIntEq,
    Builtin::BigIntCmp,
    Builtin::SymbolCreate,
    Builtin::SymbolFor,
    Builtin::SymbolKeyFor,
    Builtin::SymbolWellKnown,
    Builtin::RegExpCreate,
    Builtin::RegExpTest,
    Builtin::RegExpExec,
    Builtin::StringMatch,
    Builtin::StringReplace,
    Builtin::StringSearch,
    Builtin::StringSplit,
    Builtin::PromiseCreate,
    Builtin::PromiseInstanceResolve,
    Builtin::PromiseInstanceReject,
    Builtin::PromiseCreateResolveFunction,
    Builtin::PromiseCreateRejectFunction,
    Builtin::PromiseThen,
    Builtin::PromiseCatch,
    Builtin::PromiseFinally,
    Builtin::PromiseAll,
    Builtin::PromiseRace,
    Builtin::PromiseAllSettled,
    Builtin::PromiseAny,
    Builtin::PromiseResolveStatic,
    Builtin::PromiseRejectStatic,
    Builtin::IsPromise,
    Builtin::QueueMicrotask,
    Builtin::DrainMicrotasks,
    Builtin::AsyncFunctionStart,
    Builtin::AsyncFunctionResume,
    Builtin::AsyncFunctionSuspend,
    Builtin::ContinuationCreate,
    Builtin::ContinuationSaveVar,
    Builtin::ContinuationLoadVar,
    Builtin::AsyncGeneratorStart,
    Builtin::AsyncGeneratorNext,
    Builtin::AsyncGeneratorReturn,
    Builtin::AsyncGeneratorThrow,
    Builtin::PromiseWithResolvers,
    Builtin::IsCallable,
    Builtin::DynamicImport,
    Builtin::RegisterModuleNamespace,
    Builtin::JsxCreateElement,
    Builtin::ProxyCreate,
    Builtin::ProxyRevocable,
    Builtin::ReflectGet,
    Builtin::ReflectSet,
    Builtin::ReflectHas,
    Builtin::ReflectDeleteProperty,
    Builtin::ReflectApply,
    Builtin::ReflectConstruct,
    Builtin::ReflectGetPrototypeOf,
    Builtin::ReflectSetPrototypeOf,
    Builtin::ReflectIsExtensible,
    Builtin::ReflectPreventExtensions,
    Builtin::ReflectGetOwnPropertyDescriptor,
    Builtin::ReflectDefineProperty,
    Builtin::ReflectOwnKeys,
    Builtin::StringAt,
    Builtin::StringCharAt,
    Builtin::StringCharCodeAt,
    Builtin::StringCodePointAt,
    Builtin::StringConcatVa,
    Builtin::StringEndsWith,
    Builtin::StringIncludes,
    Builtin::StringIndexOf,
    Builtin::StringLastIndexOf,
    Builtin::StringMatchAll,
    Builtin::StringPadEnd,
    Builtin::StringPadStart,
    Builtin::StringRepeat,
    Builtin::StringReplaceAll,
    Builtin::StringSlice,
    Builtin::StringStartsWith,
    Builtin::StringSubstring,
    Builtin::StringToLowerCase,
    Builtin::StringToUpperCase,
    Builtin::StringTrim,
    Builtin::StringTrimEnd,
    Builtin::StringTrimStart,
    Builtin::StringToString,
    Builtin::StringValueOf,
    Builtin::StringIterator,
    Builtin::StringFromCharCode,
    Builtin::StringFromCodePoint,
    Builtin::MathAbs,
    Builtin::MathAcos,
    Builtin::MathAcosh,
    Builtin::MathAsin,
    Builtin::MathAsinh,
    Builtin::MathAtan,
    Builtin::MathAtanh,
    Builtin::MathAtan2,
    Builtin::MathCbrt,
    Builtin::MathCeil,
    Builtin::MathClz32,
    Builtin::MathCos,
    Builtin::MathCosh,
    Builtin::MathExp,
    Builtin::MathExpm1,
    Builtin::MathFloor,
    Builtin::MathFround,
    Builtin::MathHypot,
    Builtin::MathImul,
    Builtin::MathLog,
    Builtin::MathLog1p,
    Builtin::MathLog10,
    Builtin::MathLog2,
    Builtin::MathMax,
    Builtin::MathMin,
    Builtin::MathPow,
    Builtin::MathRandom,
    Builtin::MathRound,
    Builtin::MathSign,
    Builtin::MathSin,
    Builtin::MathSinh,
    Builtin::MathSqrt,
    Builtin::MathTan,
    Builtin::MathTanh,
    Builtin::MathTrunc,
    Builtin::NumberConstructor,
    Builtin::NumberIsNaN,
    Builtin::NumberIsFinite,
    Builtin::NumberIsInteger,
    Builtin::NumberIsSafeInteger,
    Builtin::NumberParseInt,
    Builtin::NumberParseFloat,
    Builtin::NumberProtoToString,
    Builtin::NumberProtoValueOf,
    Builtin::NumberProtoToFixed,
    Builtin::NumberProtoToExponential,
    Builtin::NumberProtoToPrecision,
    Builtin::BooleanConstructor,
    Builtin::BooleanProtoToString,
    Builtin::BooleanProtoValueOf,
    Builtin::ErrorConstructor,
    Builtin::TypeErrorConstructor,
    Builtin::RangeErrorConstructor,
    Builtin::SyntaxErrorConstructor,
    Builtin::ReferenceErrorConstructor,
    Builtin::URIErrorConstructor,
    Builtin::EvalErrorConstructor,
    Builtin::ErrorProtoToString,
    Builtin::MapConstructor,
    Builtin::MapProtoSet,
    Builtin::MapProtoGet,
    Builtin::SetConstructor,
    Builtin::SetProtoAdd,
    Builtin::MapSetHas,
    Builtin::MapSetDelete,
    Builtin::MapSetClear,
    Builtin::MapSetGetSize,
    Builtin::MapSetForEach,
    Builtin::MapSetKeys,
    Builtin::MapSetValues,
    Builtin::MapSetEntries,
    Builtin::DateConstructor,
    Builtin::DateNow,
    Builtin::DateParse,
    Builtin::DateUTC,
    Builtin::WeakMapConstructor,
    Builtin::WeakMapProtoSet,
    Builtin::WeakMapProtoGet,
    Builtin::WeakMapProtoHas,
    Builtin::WeakMapProtoDelete,
    Builtin::WeakSetConstructor,
    Builtin::WeakSetProtoAdd,
    Builtin::WeakSetProtoHas,
    Builtin::WeakSetProtoDelete,
    Builtin::SharedArrayBufferConstructor,
    Builtin::SharedArrayBufferProtoByteLength,
    Builtin::SharedArrayBufferProtoSlice,
    Builtin::SharedArrayBufferSpecies,
    Builtin::AtomicsLoad,
    Builtin::AtomicsStore,
    Builtin::AtomicsAdd,
    Builtin::AtomicsSub,
    Builtin::AtomicsAnd,
    Builtin::AtomicsOr,
    Builtin::AtomicsXor,
    Builtin::AtomicsExchange,
    Builtin::AtomicsCompareExchange,
    Builtin::AtomicsIsLockFree,
    Builtin::AtomicsWait,
    Builtin::AtomicsNotify,
    Builtin::AtomicsWaitAsync,
    Builtin::WeakRefConstructor,
    Builtin::WeakRefProtoDeref,
    Builtin::FinalizationRegistryConstructor,
    Builtin::FinalizationRegistryProtoRegister,
    Builtin::FinalizationRegistryProtoUnregister,
    Builtin::ArrayBufferConstructor,
    Builtin::ArrayBufferProtoByteLength,
    Builtin::ArrayBufferProtoSlice,
    Builtin::DataViewConstructor,
    Builtin::DataViewProtoGetFloat64,
    Builtin::DataViewProtoGetFloat32,
    Builtin::DataViewProtoGetInt32,
    Builtin::DataViewProtoGetUint32,
    Builtin::DataViewProtoGetInt16,
    Builtin::DataViewProtoGetUint16,
    Builtin::DataViewProtoGetInt8,
    Builtin::DataViewProtoGetUint8,
    Builtin::DataViewProtoSetFloat64,
    Builtin::DataViewProtoSetFloat32,
    Builtin::DataViewProtoSetInt32,
    Builtin::DataViewProtoSetUint32,
    Builtin::DataViewProtoSetInt16,
    Builtin::DataViewProtoSetUint16,
    Builtin::DataViewProtoSetInt8,
    Builtin::DataViewProtoSetUint8,
    Builtin::Int8ArrayConstructor,
    Builtin::Uint8ArrayConstructor,
    Builtin::Uint8ClampedArrayConstructor,
    Builtin::Int16ArrayConstructor,
    Builtin::Uint16ArrayConstructor,
    Builtin::Int32ArrayConstructor,
    Builtin::Uint32ArrayConstructor,
    Builtin::Float32ArrayConstructor,
    Builtin::Float64ArrayConstructor,
    Builtin::TypedArrayProtoLength,
    Builtin::TypedArrayProtoByteLength,
    Builtin::TypedArrayProtoByteOffset,
    Builtin::TypedArrayProtoSet,
    Builtin::TypedArrayProtoSlice,
    Builtin::TypedArrayProtoSubarray,
    Builtin::BigInt64ArrayConstructor,
    Builtin::BigUint64ArrayConstructor,
    Builtin::TypedArrayProtoFill,
    Builtin::TypedArrayProtoReverse,
    Builtin::TypedArrayProtoIndexOf,
    Builtin::TypedArrayProtoLastIndexOf,
    Builtin::TypedArrayProtoIncludes,
    Builtin::TypedArrayProtoJoin,
    Builtin::TypedArrayProtoToString,
    Builtin::TypedArrayProtoCopyWithin,
    Builtin::TypedArrayProtoAt,
    Builtin::TypedArrayProtoForEach,
    Builtin::TypedArrayProtoMap,
    Builtin::TypedArrayProtoFilter,
    Builtin::TypedArrayProtoReduce,
    Builtin::TypedArrayProtoReduceRight,
    Builtin::TypedArrayProtoFind,
    Builtin::TypedArrayProtoFindIndex,
    Builtin::TypedArrayProtoSome,
    Builtin::TypedArrayProtoEvery,
    Builtin::TypedArrayProtoSort,
    Builtin::TypedArrayProtoEntries,
    Builtin::TypedArrayProtoKeys,
    Builtin::TypedArrayProtoValues,
    Builtin::GetBuiltinGlobal,
    Builtin::CreateGlobalObject,
    Builtin::CreateException,
    Builtin::ExceptionValue,
    Builtin::NewTarget,
    Builtin::CreateUnmappedArgumentsObject,
    Builtin::CreateMappedArgumentsObject,
    Builtin::ScopeRecordCreate,
    Builtin::ScopeRecordAddBinding,
    Builtin::EvalGetBinding,
    Builtin::EvalSetBinding,
    Builtin::EvalHasBinding,
    Builtin::EvalSuperBase,
    Builtin::ScopeRecordSetMeta,
    Builtin::ScopeRecordDestroy,
];
