use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Builtin {
    ConsoleLog,
    ConsoleError,
    ConsoleWarn,
    ConsoleInfo,
    ConsoleDebug,
    ConsoleTrace,
    Debugger,
    Throw,
    AbortShadowStackOverflow,
    F64Mod,
    F64Exp,
    IteratorFrom,
    IteratorNext,
    IteratorClose,
    AsyncIteratorFrom,
    IteratorValue,
    IteratorDone,
    EnumeratorFrom,
    EnumeratorNext,
    EnumeratorKey,
    EnumeratorDone,
    // 运算符
    TypeOf,
    In,
    InstanceOf,
    AbstractEq,
    StrictEq,
    AbstractCompare,
    // 对象属性描述符
    DefineProperty,
    GetOwnPropDesc,
    // 宿主 API
    SetTimeout,
    ClearTimeout,
    SetInterval,
    ClearInterval,
    Fetch,
    HeadersConstructor,
    RequestConstructor,
    ResponseConstructor,
    AbortControllerConstructor,
    Eval,
    EvalIndirect,
    EvalResult,
    JsonStringify,
    JsonParse,
    CreateClosure,
    // 数组方法
    ArrayPush,
    ArrayPushSpread,
    ArrayPop,
    ArrayIncludes,
    ArrayIndexOf,
    ArrayJoin,
    ArrayConcat,
    ArraySlice,
    ArrayFill,
    ArrayReverse,
    ArrayFlat,
    ArrayInitLength,
    ArrayGetLength,
    // ── 新数组方法 ──
    ArrayShift,
    ArrayUnshiftVa,
    ArraySort,
    ArrayAt,
    ArrayCopyWithin,
    ArrayForEach,
    ArrayMap,
    ArrayFilter,
    ArrayReduce,
    ArrayReduceRight,
    ArrayFind,
    ArrayFindIndex,
    ArraySome,
    ArrayEvery,
    ArrayFlatMap,
    ArrayIsArray,
    ArrayFrom,
    ArraySpliceVa,
    ArrayConcatVa,
    // ── 函数原型方法 ──
    FuncCall,
    FuncApply,
    FuncBind,
    // ── 对象解构 rest ──
    ObjectRest,
    // ── new.prototype 修复 ──
    GetPrototypeFromConstructor,
    // ── Object 原型方法 ──
    HasOwnProperty,
    PrivateGet,
    PrivateSet,
    PrivateHas,
    ObjectProtoToString,
    ObjectProtoValueOf,
    // ── Object 静态方法 ──
    ObjectKeys,
    ObjectValues,
    ObjectEntries,
    ObjectAssign,
    ObjectCreate,
    ObjectGetPrototypeOf,
    ObjectSetPrototypeOf,
    ObjectGetOwnPropertyNames,
    ObjectGetOwnPropertySymbols,
    ObjectIs,
    ObjectGroupBy,
    ObjectIsExtensible,
    ObjectPreventExtensions,
    // ── Map.groupBy ──
    MapGroupBy,
    // ── BigInt operations ──────────────────────────────────────────────
    BigIntFromLiteral,
    BigIntAdd,
    BigIntSub,
    BigIntMul,
    BigIntDiv,
    BigIntMod,
    BigIntPow,
    BigIntNeg,
    BigIntEq,
    BigIntCmp,
    // ── Symbol operations ──────────────────────────────────────────────
    SymbolCreate,
    SymbolFor,
    SymbolKeyFor,
    // ── Well-known symbols ─────────────────────────────────────────────
    SymbolWellKnown,
    // ── RegExp operations ──────────────────────────────────────────────
    RegExpCreate,
    RegExpTest,
    RegExpExec,
    // ── String prototype methods ───────────────────────────────────────
    StringMatch,
    StringReplace,
    StringSearch,
    StringSplit,
    PromiseCreate,
    PromiseInstanceResolve,
    PromiseInstanceReject,
    PromiseCreateResolveFunction,
    PromiseCreateRejectFunction,
    PromiseThen,
    PromiseCatch,
    PromiseFinally,
    PromiseAll,
    PromiseRace,
    PromiseAllSettled,
    PromiseAny,
    PromiseResolveStatic,
    PromiseRejectStatic,
    IsPromise,
    QueueMicrotask,
    DrainMicrotasks,
    AsyncFunctionStart,
    AsyncFunctionResume,
    AsyncFunctionSuspend,
    ContinuationCreate,
    ContinuationSaveVar,
    ContinuationLoadVar,
    AsyncGeneratorStart,
    AsyncGeneratorNext,
    AsyncGeneratorReturn,
    AsyncGeneratorThrow,
    PromiseWithResolvers,
    IsCallable,
    // ── 动态 import ──────────────────────────────────────────────────
    DynamicImport,
    RegisterModuleNamespace,
    // ── JSX ────────────────────────────────────────────────────────────
    JsxCreateElement,
    // ── Proxy / Reflect ────────────────────────────────────────────────
    ProxyCreate,
    ProxyRevocable,
    ReflectGet,
    ReflectSet,
    ReflectHas,
    ReflectDeleteProperty,
    ReflectApply,
    ReflectConstruct,
    ReflectGetPrototypeOf,
    ReflectSetPrototypeOf,
    ReflectIsExtensible,
    ReflectPreventExtensions,
    ReflectGetOwnPropertyDescriptor,
    ReflectDefineProperty,
    ReflectOwnKeys,
    // ── String 完整方法 ──
    StringAt,
    StringCharAt,
    StringCharCodeAt,
    StringCodePointAt,
    StringConcatVa,
    StringEndsWith,
    StringIncludes,
    StringIndexOf,
    StringLastIndexOf,
    StringMatchAll,
    StringPadEnd,
    StringPadStart,
    StringRepeat,
    StringReplaceAll,
    StringSlice,
    StringStartsWith,
    StringSubstring,
    StringToLowerCase,
    StringToUpperCase,
    StringTrim,
    StringTrimEnd,
    StringTrimStart,
    StringToString,
    StringValueOf,
    StringIterator,
    StringFromCharCode,
    StringFromCodePoint,
    // ── Math static methods ────────────────────────────────────────────
    MathAbs,
    MathAcos,
    MathAcosh,
    MathAsin,
    MathAsinh,
    MathAtan,
    MathAtanh,
    MathAtan2,
    MathCbrt,
    MathCeil,
    MathClz32,
    MathCos,
    MathCosh,
    MathExp,
    MathExpm1,
    MathFloor,
    MathFround,
    MathHypot,
    MathImul,
    MathLog,
    MathLog1p,
    MathLog10,
    MathLog2,
    MathMax,
    MathMin,
    MathPow,
    MathRandom,
    MathRound,
    MathSign,
    MathSin,
    MathSinh,
    MathSqrt,
    MathTan,
    MathTanh,
    MathTrunc,
    // ── Number built-in ────────────────────────────────────────────────
    NumberConstructor,
    NumberIsNaN,
    NumberIsFinite,
    NumberIsInteger,
    NumberIsSafeInteger,
    NumberParseInt,
    NumberParseFloat,
    NumberProtoToString,
    NumberProtoValueOf,
    NumberProtoToFixed,
    NumberProtoToExponential,
    NumberProtoToPrecision,
    // ── Boolean built-in ───────────────────────────────────────────────
    BooleanConstructor,
    BooleanProtoToString,
    BooleanProtoValueOf,
    // ── Error built-in ─────────────────────────────────────────────────
    ErrorConstructor,
    TypeErrorConstructor,
    RangeErrorConstructor,
    SyntaxErrorConstructor,
    ReferenceErrorConstructor,
    URIErrorConstructor,
    EvalErrorConstructor,
    ErrorProtoToString,
    // ── Map built-in ──────────────────────────────────────────────────
    MapConstructor,
    MapProtoSet,
    MapProtoGet,
    // ── Set built-in ──────────────────────────────────────────────────
    SetConstructor,
    SetProtoAdd,
    // ── Map/Set shared methods (dispatch at runtime) ──────────────────
    MapSetHas,
    MapSetDelete,
    MapSetClear,
    MapSetGetSize,
    MapSetForEach,
    MapSetKeys,
    MapSetValues,
    MapSetEntries,
    // ── Date built-in ─────────────────────────────────────────────────
    DateConstructor,
    DateNow,
    DateParse,
    DateUTC,
    // ── WeakMap built-in ──────────────────────────────────────────────
    WeakMapConstructor,
    WeakMapProtoSet,
    WeakMapProtoGet,
    WeakMapProtoHas,
    WeakMapProtoDelete,
    // ── WeakSet built-in ──────────────────────────────────────────────
    WeakSetConstructor,
    WeakSetProtoAdd,
    WeakSetProtoHas,
    WeakSetProtoDelete,
    // ── SharedArrayBuffer built-in ──
    SharedArrayBufferConstructor,
    SharedArrayBufferProtoByteLength,
    SharedArrayBufferProtoGrow,
    SharedArrayBufferProtoGrowable,
    SharedArrayBufferProtoMaxByteLength,
    SharedArrayBufferProtoSlice,
    SharedArrayBufferSpecies,
    // ── Atomics built-in ──
    AtomicsLoad,
    AtomicsStore,
    AtomicsAdd,
    AtomicsSub,
    AtomicsAnd,
    AtomicsOr,
    AtomicsXor,
    AtomicsExchange,
    AtomicsCompareExchange,
    AtomicsIsLockFree,
    AtomicsPause,
    AtomicsWait,
    AtomicsNotify,
    AtomicsWaitAsync,
    // ── WeakRef built-in ──────────────────────────────────────────────
    WeakRefConstructor,
    WeakRefProtoDeref,
    // ── FinalizationRegistry built-in ─────────────────────────────────
    FinalizationRegistryConstructor,
    FinalizationRegistryProtoRegister,
    FinalizationRegistryProtoUnregister,
    // ── ArrayBuffer built-in ──────────────────────────────────────────
    ArrayBufferConstructor,
    ArrayBufferProtoByteLength,
    ArrayBufferProtoSlice,
    // ── DataView built-in ──────────────────────────────────────────────
    DataViewConstructor,
    DataViewProtoGetFloat64,
    DataViewProtoGetFloat32,
    DataViewProtoGetInt32,
    DataViewProtoGetUint32,
    DataViewProtoGetInt16,
    DataViewProtoGetUint16,
    DataViewProtoGetInt8,
    DataViewProtoGetUint8,
    DataViewProtoSetFloat64,
    DataViewProtoSetFloat32,
    DataViewProtoSetInt32,
    DataViewProtoSetUint32,
    DataViewProtoSetInt16,
    DataViewProtoSetUint16,
    DataViewProtoSetInt8,
    DataViewProtoSetUint8,
    // ── TypedArray constructors ────────────────────────────────────────
    Int8ArrayConstructor,
    Uint8ArrayConstructor,
    Uint8ClampedArrayConstructor,
    Int16ArrayConstructor,
    Uint16ArrayConstructor,
    Int32ArrayConstructor,
    Uint32ArrayConstructor,
    Float32ArrayConstructor,
    Float64ArrayConstructor,
    // ── TypedArray prototype methods ───────────────────────────────────
    TypedArrayProtoLength,
    TypedArrayProtoByteLength,
    TypedArrayProtoByteOffset,
    TypedArrayProtoSet,
    TypedArrayProtoSlice,
    TypedArrayProtoSubarray,
    // ── TypedArray 新增构造器 ──
    BigInt64ArrayConstructor,
    BigUint64ArrayConstructor,
    // ── TypedArray 新增原型方法 — 简单方法 ──
    TypedArrayProtoFill,
    TypedArrayProtoReverse,
    TypedArrayProtoIndexOf,
    TypedArrayProtoLastIndexOf,
    TypedArrayProtoIncludes,
    TypedArrayProtoJoin,
    TypedArrayProtoToString,
    TypedArrayProtoCopyWithin,
    TypedArrayProtoAt,
    // ── TypedArray 新增原型方法 — 回调方法 (Type 12) ──
    TypedArrayProtoForEach,
    TypedArrayProtoMap,
    TypedArrayProtoFilter,
    TypedArrayProtoReduce,
    TypedArrayProtoReduceRight,
    TypedArrayProtoFind,
    TypedArrayProtoFindIndex,
    TypedArrayProtoSome,
    TypedArrayProtoEvery,
    TypedArrayProtoSort,
    // ── TypedArray 迭代器方法 ──
    TypedArrayProtoEntries,
    TypedArrayProtoKeys,
    TypedArrayProtoValues,
    GetBuiltinGlobal,
    CreateGlobalObject,
    CreateException,
    ExceptionValue,
    // ── Eval exception check ──
    IsException,
    // ── new.target meta property ──
    NewTarget,
    // ── Arguments Exotic Object ──
    CreateUnmappedArgumentsObject,
    CreateMappedArgumentsObject,
    // ── ScopeRecord eval bridge ───────────────────────────────────────
    /// dest: i64 — scope record handle
    ScopeRecordCreate,
    /// args[0]: record, args[1]: name (string), args[2]: value (i64), args[3]: is_tdz (bool), args[4]: is_const (bool)
    ScopeRecordAddBinding,
    /// dest: i64 — value (or TAG_EXCEPTION if TDZ)
    EvalGetBinding,
    /// dest: i64 — written value
    EvalSetBinding,
    /// dest: i64 — bool (0 or 1)
    EvalHasBinding,
    /// dest: i64 — prototype | undefined | TAG_EXCEPTION
    EvalSuperBase,
    /// args[0]: record, args[1]: key (i64 integer tag), args[2]: value (i64)
    ScopeRecordSetMeta,
    /// args[0]: record — removes the scope record from the runtime map
    ScopeRecordDestroy,
    // ── WHATWG Streams ──
    ReadableStreamConstructor,
    WritableStreamConstructor,
    TransformStreamConstructor,
    CountQueuingStrategyConstructor,
    ByteLengthQueuingStrategyConstructor,
}

impl fmt::Display for Builtin {
    // 按类别分派到辅助函数，每个辅助函数处理一组相关变体
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = self.fmt_console_iterator_str()
            .or_else(|| self.fmt_host_api_str())
            .or_else(|| self.fmt_array_str())
            .or_else(|| self.fmt_func_object_str())
            .or_else(|| self.fmt_bigint_regexp_str())
            .or_else(|| self.fmt_promise_async_str())
            .or_else(|| self.fmt_proxy_reflect_str())
            .or_else(|| self.fmt_math_str())
            .or_else(|| self.fmt_number_boolean_error_str())
            .or_else(|| self.fmt_collection_date_str())
            .or_else(|| self.fmt_weak_buffer_str())
            .or_else(|| self.fmt_dataview_typed_array_str())
            .or_else(|| self.fmt_misc_str())
            .expect("missing Builtin Display arm");
        formatter.write_str(s)
    }
}

// ── 各类别的字符串映射辅助函数 ───────────────────────────────────────

impl Builtin {
    /// Console / debugger / 迭代器 / 枚举器 / 运算符 / 属性描述符
    fn fmt_console_iterator_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::ConsoleLog => "console.log",
            Self::ConsoleError => "console.error",
            Self::ConsoleWarn => "console.warn",
            Self::ConsoleInfo => "console.info",
            Self::ConsoleDebug => "console.debug",
            Self::ConsoleTrace => "console.trace",
            Self::Debugger => "debugger",
            Self::Throw => "throw",
            Self::AbortShadowStackOverflow => "abort_shadow_stack_overflow",
            Self::F64Mod => "f64.mod",
            Self::F64Exp => "f64.exp",
            Self::IteratorFrom => "iterator.from",
            Self::IteratorNext => "iterator.next",
            Self::IteratorClose => "iterator.close",
            Self::AsyncIteratorFrom => "async_iterator.from",
            Self::IteratorValue => "iterator.value",
            Self::IteratorDone => "iterator.done",
            Self::EnumeratorFrom => "enumerator.from",
            Self::EnumeratorNext => "enumerator.next",
            Self::EnumeratorKey => "enumerator.key",
            Self::EnumeratorDone => "enumerator.done",
            Self::TypeOf => "typeof",
            Self::In => "op_in",
            Self::InstanceOf => "op_instanceof",
            Self::StrictEq => "strict_eq",
            Self::AbstractEq => "abstract_eq",
            Self::AbstractCompare => "abstract_compare",
            Self::DefineProperty => "define_property",
            Self::GetOwnPropDesc => "get_own_prop_desc",
            _ => return None,
        })
    }

    /// 宿主 API（setTimeout / fetch / eval / JSON / closure）
    fn fmt_host_api_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::SetTimeout => "setTimeout",
            Self::ClearTimeout => "clearTimeout",
            Self::SetInterval => "setInterval",
            Self::ClearInterval => "clearInterval",
            Self::Fetch => "fetch",
            Self::HeadersConstructor => "Headers",
            Self::RequestConstructor => "Request",
            Self::ResponseConstructor => "Response",
            Self::AbortControllerConstructor => "AbortController",
            Self::Eval => "eval",
            Self::EvalIndirect => "eval.indirect",
            Self::EvalResult => "eval.result",
            Self::JsonStringify => "JSON.stringify",
            Self::JsonParse => "JSON.parse",
            Self::CreateClosure => "create_closure",
            _ => return None,
        })
    }

    /// 数组方法
    fn fmt_array_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::ArrayPush => "array.push",
            Self::ArrayPushSpread => "array.push_spread",
            Self::ArrayPop => "array.pop",
            Self::ArrayIncludes => "array.includes",
            Self::ArrayIndexOf => "array.index_of",
            Self::ArrayJoin => "array.join",
            Self::ArrayConcat => "array.concat",
            Self::ArraySlice => "array.slice",
            Self::ArrayFill => "array.fill",
            Self::ArrayReverse => "array.reverse",
            Self::ArrayFlat => "array.flat",
            Self::ArrayInitLength => "array.init_length",
            Self::ArrayGetLength => "array.get_length",
            Self::ArrayShift => "array.shift",
            Self::ArrayUnshiftVa => "array.unshift",
            Self::ArraySort => "array.sort",
            Self::ArrayAt => "array.at",
            Self::ArrayCopyWithin => "array.copy_within",
            Self::ArrayForEach => "array.for_each",
            Self::ArrayMap => "array.map",
            Self::ArrayFilter => "array.filter",
            Self::ArrayReduce => "array.reduce",
            Self::ArrayReduceRight => "array.reduce_right",
            Self::ArrayFind => "array.find",
            Self::ArrayFindIndex => "array.find_index",
            Self::ArraySome => "array.some",
            Self::ArrayEvery => "array.every",
            Self::ArrayFlatMap => "array.flat_map",
            Self::ArrayIsArray => "array.is_array",
            Self::ArrayFrom => "array.from",
            Self::ArraySpliceVa => "array.splice_va",
            Self::ArrayConcatVa => "array.concat_va",
            _ => return None,
        })
    }

    /// 函数原型方法 / 对象方法 / Map.groupBy
    fn fmt_func_object_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::FuncCall => "func_call",
            Self::FuncApply => "func_apply",
            Self::FuncBind => "func_bind",
            Self::ObjectRest => "object_rest",
            Self::GetPrototypeFromConstructor => "get_prototype_from_constructor",
            Self::HasOwnProperty => "has_own_property",
            Self::PrivateGet => "private_get",
            Self::PrivateSet => "private_set",
            Self::PrivateHas => "private_has",
            Self::ObjectProtoToString => "object_proto_to_string",
            Self::ObjectProtoValueOf => "object_proto_value_of",
            Self::ObjectKeys => "object.keys",
            Self::ObjectValues => "object.values",
            Self::ObjectEntries => "object.entries",
            Self::ObjectAssign => "object.assign",
            Self::ObjectCreate => "object.create",
            Self::ObjectGetPrototypeOf => "object.get_prototype_of",
            Self::ObjectSetPrototypeOf => "object.set_prototype_of",
            Self::ObjectGetOwnPropertyNames => "object.get_own_property_names",
            Self::ObjectGetOwnPropertySymbols => "object.get_own_property_symbols",
            Self::ObjectIs => "object.is",
            Self::ObjectGroupBy => "object.group_by",
            Self::ObjectIsExtensible => "object.is_extensible",
            Self::ObjectPreventExtensions => "object.prevent_extensions",
            Self::MapGroupBy => "map.group_by",
            _ => return None,
        })
    }

    /// BigInt / Symbol / RegExp / 基础字符串方法
    fn fmt_bigint_regexp_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::BigIntFromLiteral => "bigint.from_literal",
            Self::BigIntAdd => "bigint.add",
            Self::BigIntSub => "bigint.sub",
            Self::BigIntMul => "bigint.mul",
            Self::BigIntDiv => "bigint.div",
            Self::BigIntMod => "bigint.mod",
            Self::BigIntPow => "bigint.pow",
            Self::BigIntNeg => "bigint.neg",
            Self::BigIntEq => "bigint.eq",
            Self::BigIntCmp => "bigint.cmp",
            Self::SymbolCreate => "symbol.create",
            Self::SymbolFor => "symbol.for",
            Self::SymbolKeyFor => "symbol.key_for",
            Self::SymbolWellKnown => "symbol.well_known",
            Self::RegExpCreate => "regexp.create",
            Self::RegExpTest => "regexp.test",
            Self::RegExpExec => "regexp.exec",
            Self::StringMatch => "string.match",
            Self::StringReplace => "string.replace",
            Self::StringSearch => "string.search",
            Self::StringSplit => "string.split",
            _ => return None,
        })
    }

    /// Promise / async / continuation / generator
    fn fmt_promise_async_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::PromiseCreate => "promise.create",
            Self::PromiseInstanceResolve => "promise.instance_resolve",
            Self::PromiseInstanceReject => "promise.instance_reject",
            Self::PromiseCreateResolveFunction => "promise.create_resolve_function",
            Self::PromiseCreateRejectFunction => "promise.create_reject_function",
            Self::PromiseThen => "promise.then",
            Self::PromiseCatch => "promise.catch",
            Self::PromiseFinally => "promise.finally",
            Self::PromiseAll => "promise.all",
            Self::PromiseRace => "promise.race",
            Self::PromiseAllSettled => "promise.all_settled",
            Self::PromiseAny => "promise.any",
            Self::PromiseResolveStatic => "promise.resolve_static",
            Self::PromiseRejectStatic => "promise.reject_static",
            Self::IsPromise => "is_promise",
            Self::QueueMicrotask => "queue_microtask",
            Self::DrainMicrotasks => "drain_microtasks",
            Self::AsyncFunctionStart => "async_function.start",
            Self::AsyncFunctionResume => "async_function.resume",
            Self::AsyncFunctionSuspend => "async_function.suspend",
            Self::ContinuationCreate => "continuation.create",
            Self::ContinuationSaveVar => "continuation.save_var",
            Self::ContinuationLoadVar => "continuation.load_var",
            Self::AsyncGeneratorStart => "async_generator.start",
            Self::AsyncGeneratorNext => "async_generator.next",
            Self::AsyncGeneratorReturn => "async_generator.return",
            Self::PromiseWithResolvers => "promise.with_resolvers",
            Self::IsCallable => "is_callable",
            Self::AsyncGeneratorThrow => "async_generator.throw",
            _ => return None,
        })
    }

    /// 动态 import / JSX / Proxy / Reflect / 完整字符串方法
    fn fmt_proxy_reflect_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::DynamicImport => "dynamic_import",
            Self::RegisterModuleNamespace => "register_module_namespace",
            Self::JsxCreateElement => "jsx.create_element",
            Self::ProxyCreate => "proxy.create",
            Self::ProxyRevocable => "proxy.revocable",
            Self::ReflectGet => "reflect.get",
            Self::ReflectSet => "reflect.set",
            Self::ReflectHas => "reflect.has",
            Self::ReflectDeleteProperty => "reflect.delete_property",
            Self::ReflectApply => "reflect.apply",
            Self::ReflectConstruct => "reflect.construct",
            Self::ReflectGetPrototypeOf => "reflect.get_prototype_of",
            Self::ReflectSetPrototypeOf => "reflect.set_prototype_of",
            Self::ReflectIsExtensible => "reflect.is_extensible",
            Self::ReflectPreventExtensions => "reflect.prevent_extensions",
            Self::ReflectGetOwnPropertyDescriptor => "reflect.get_own_property_descriptor",
            Self::ReflectDefineProperty => "reflect.define_property",
            Self::ReflectOwnKeys => "reflect.own_keys",
            Self::StringAt => "string.at",
            Self::StringCharAt => "string.char_at",
            Self::StringCharCodeAt => "string.char_code_at",
            Self::StringCodePointAt => "string.code_point_at",
            Self::StringConcatVa => "string.concat_va",
            Self::StringEndsWith => "string.ends_with",
            Self::StringIncludes => "string.includes",
            Self::StringIndexOf => "string.index_of",
            Self::StringLastIndexOf => "string.last_index_of",
            Self::StringMatchAll => "string.match_all",
            Self::StringPadEnd => "string.pad_end",
            Self::StringPadStart => "string.pad_start",
            Self::StringRepeat => "string.repeat",
            Self::StringReplaceAll => "string.replace_all",
            Self::StringSlice => "string.slice",
            Self::StringStartsWith => "string.starts_with",
            Self::StringSubstring => "string.substring",
            Self::StringToLowerCase => "string.to_lower_case",
            Self::StringToUpperCase => "string.to_upper_case",
            Self::StringTrim => "string.trim",
            Self::StringTrimEnd => "string.trim_end",
            Self::StringTrimStart => "string.trim_start",
            Self::StringToString => "string.to_string",
            Self::StringValueOf => "string.value_of",
            Self::StringIterator => "string.iterator",
            Self::StringFromCharCode => "string.from_char_code",
            Self::StringFromCodePoint => "string.from_code_point",
            _ => return None,
        })
    }

    /// Math 静态方法
    fn fmt_math_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::MathAbs => "Math.abs",
            Self::MathAcos => "Math.acos",
            Self::MathAcosh => "Math.acosh",
            Self::MathAsin => "Math.asin",
            Self::MathAsinh => "Math.asinh",
            Self::MathAtan => "Math.atan",
            Self::MathAtanh => "Math.atanh",
            Self::MathAtan2 => "Math.atan2",
            Self::MathCbrt => "Math.cbrt",
            Self::MathCeil => "Math.ceil",
            Self::MathClz32 => "Math.clz32",
            Self::MathCos => "Math.cos",
            Self::MathCosh => "Math.cosh",
            Self::MathExp => "Math.exp",
            Self::MathExpm1 => "Math.expm1",
            Self::MathFloor => "Math.floor",
            Self::MathFround => "Math.fround",
            Self::MathHypot => "Math.hypot",
            Self::MathImul => "Math.imul",
            Self::MathLog => "Math.log",
            Self::MathLog1p => "Math.log1p",
            Self::MathLog10 => "Math.log10",
            Self::MathLog2 => "Math.log2",
            Self::MathMax => "Math.max",
            Self::MathMin => "Math.min",
            Self::MathPow => "Math.pow",
            Self::MathRandom => "Math.random",
            Self::MathRound => "Math.round",
            Self::MathSign => "Math.sign",
            Self::MathSin => "Math.sin",
            Self::MathSinh => "Math.sinh",
            Self::MathSqrt => "Math.sqrt",
            Self::MathTan => "Math.tan",
            Self::MathTanh => "Math.tanh",
            Self::MathTrunc => "Math.trunc",
            _ => return None,
        })
    }

    /// Number / Boolean / Error 内建对象
    fn fmt_number_boolean_error_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::NumberConstructor => "Number",
            Self::NumberIsNaN => "Number.isNaN",
            Self::NumberIsFinite => "Number.isFinite",
            Self::NumberIsInteger => "Number.isInteger",
            Self::NumberIsSafeInteger => "Number.isSafeInteger",
            Self::NumberParseInt => "Number.parseInt",
            Self::NumberParseFloat => "Number.parseFloat",
            Self::NumberProtoToString => "Number.prototype.toString",
            Self::NumberProtoValueOf => "Number.prototype.valueOf",
            Self::NumberProtoToFixed => "Number.prototype.toFixed",
            Self::NumberProtoToExponential => "Number.prototype.toExponential",
            Self::NumberProtoToPrecision => "Number.prototype.toPrecision",
            Self::BooleanConstructor => "Boolean",
            Self::BooleanProtoToString => "Boolean.prototype.toString",
            Self::BooleanProtoValueOf => "Boolean.prototype.valueOf",
            Self::ErrorConstructor => "Error",
            Self::TypeErrorConstructor => "TypeError",
            Self::RangeErrorConstructor => "RangeError",
            Self::SyntaxErrorConstructor => "SyntaxError",
            Self::ReferenceErrorConstructor => "ReferenceError",
            Self::URIErrorConstructor => "URIError",
            Self::EvalErrorConstructor => "EvalError",
            Self::ErrorProtoToString => "Error.prototype.toString",
            _ => return None,
        })
    }

    /// Map / Set / Date 内建对象
    fn fmt_collection_date_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::MapConstructor => "Map",
            Self::MapProtoSet => "Map.prototype.set",
            Self::MapProtoGet => "Map.prototype.get",
            Self::SetConstructor => "Set",
            Self::SetProtoAdd => "Set.prototype.add",
            Self::MapSetHas => "MapSet.has",
            Self::MapSetDelete => "MapSet.delete",
            Self::MapSetClear => "MapSet.clear",
            Self::MapSetGetSize => "MapSet.size",
            Self::MapSetForEach => "MapSet.forEach",
            Self::MapSetKeys => "MapSet.keys",
            Self::MapSetValues => "MapSet.values",
            Self::MapSetEntries => "MapSet.entries",
            Self::DateConstructor => "Date",
            Self::DateNow => "Date.now",
            Self::DateParse => "Date.parse",
            Self::DateUTC => "Date.UTC",
            _ => return None,
        })
    }

    /// WeakMap / WeakSet / SharedArrayBuffer / Atomics / WeakRef / FinalizationRegistry
    fn fmt_weak_buffer_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::WeakMapConstructor => "WeakMap",
            Self::WeakMapProtoSet => "WeakMap.prototype.set",
            Self::WeakMapProtoGet => "WeakMap.prototype.get",
            Self::WeakMapProtoHas => "WeakMap.prototype.has",
            Self::WeakMapProtoDelete => "WeakMap.prototype.delete",
            Self::WeakSetConstructor => "WeakSet",
            Self::WeakSetProtoAdd => "WeakSet.prototype.add",
            Self::WeakSetProtoHas => "WeakSet.prototype.has",
            Self::WeakSetProtoDelete => "WeakSet.prototype.delete",
            Self::SharedArrayBufferConstructor => "SharedArrayBuffer",
            Self::SharedArrayBufferProtoByteLength => "SharedArrayBuffer.prototype.byteLength",
            Self::SharedArrayBufferProtoGrow => "SharedArrayBuffer.prototype.grow",
            Self::SharedArrayBufferProtoGrowable => "SharedArrayBuffer.prototype.growable",
            Self::SharedArrayBufferProtoMaxByteLength => {
                "SharedArrayBuffer.prototype.maxByteLength"
            }
            Self::SharedArrayBufferProtoSlice => "SharedArrayBuffer.prototype.slice",
            Self::SharedArrayBufferSpecies => "SharedArrayBuffer[Symbol.species]",
            Self::AtomicsLoad => "Atomics.load",
            Self::AtomicsStore => "Atomics.store",
            Self::AtomicsAdd => "Atomics.add",
            Self::AtomicsSub => "Atomics.sub",
            Self::AtomicsAnd => "Atomics.and",
            Self::AtomicsOr => "Atomics.or",
            Self::AtomicsXor => "Atomics.xor",
            Self::AtomicsExchange => "Atomics.exchange",
            Self::AtomicsCompareExchange => "Atomics.compareExchange",
            Self::AtomicsIsLockFree => "Atomics.isLockFree",
            Self::AtomicsPause => "Atomics.pause",
            Self::AtomicsWait => "Atomics.wait",
            Self::AtomicsNotify => "Atomics.notify",
            Self::AtomicsWaitAsync => "Atomics.waitAsync",
            Self::WeakRefConstructor => "WeakRef",
            Self::WeakRefProtoDeref => "WeakRef.prototype.deref",
            Self::FinalizationRegistryConstructor => "FinalizationRegistry",
            Self::FinalizationRegistryProtoRegister => "FinalizationRegistry.prototype.register",
            Self::FinalizationRegistryProtoUnregister => {
                "FinalizationRegistry.prototype.unregister"
            }
            _ => return None,
        })
    }

    /// ArrayBuffer / DataView / TypedArray
    fn fmt_dataview_typed_array_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::ArrayBufferConstructor => "ArrayBuffer",
            Self::ArrayBufferProtoByteLength => "ArrayBuffer.prototype.byteLength",
            Self::ArrayBufferProtoSlice => "ArrayBuffer.prototype.slice",
            Self::DataViewConstructor => "DataView",
            Self::DataViewProtoGetFloat64 => "DataView.prototype.getFloat64",
            Self::DataViewProtoGetFloat32 => "DataView.prototype.getFloat32",
            Self::DataViewProtoGetInt32 => "DataView.prototype.getInt32",
            Self::DataViewProtoGetUint32 => "DataView.prototype.getUint32",
            Self::DataViewProtoGetInt16 => "DataView.prototype.getInt16",
            Self::DataViewProtoGetUint16 => "DataView.prototype.getUint16",
            Self::DataViewProtoGetInt8 => "DataView.prototype.getInt8",
            Self::DataViewProtoGetUint8 => "DataView.prototype.getUint8",
            Self::DataViewProtoSetFloat64 => "DataView.prototype.setFloat64",
            Self::DataViewProtoSetFloat32 => "DataView.prototype.setFloat32",
            Self::DataViewProtoSetInt32 => "DataView.prototype.setInt32",
            Self::DataViewProtoSetUint32 => "DataView.prototype.setUint32",
            Self::DataViewProtoSetInt16 => "DataView.prototype.setInt16",
            Self::DataViewProtoSetUint16 => "DataView.prototype.setUint16",
            Self::DataViewProtoSetInt8 => "DataView.prototype.setInt8",
            Self::DataViewProtoSetUint8 => "DataView.prototype.setUint8",
            Self::Int8ArrayConstructor => "Int8Array",
            Self::Uint8ArrayConstructor => "Uint8Array",
            Self::Uint8ClampedArrayConstructor => "Uint8ClampedArray",
            Self::Int16ArrayConstructor => "Int16Array",
            Self::Uint16ArrayConstructor => "Uint16Array",
            Self::Int32ArrayConstructor => "Int32Array",
            Self::Uint32ArrayConstructor => "Uint32Array",
            Self::Float32ArrayConstructor => "Float32Array",
            Self::Float64ArrayConstructor => "Float64Array",
            Self::TypedArrayProtoLength => "TypedArray.prototype.length",
            Self::TypedArrayProtoByteLength => "TypedArray.prototype.byteLength",
            Self::TypedArrayProtoByteOffset => "TypedArray.prototype.byteOffset",
            Self::TypedArrayProtoSet => "TypedArray.prototype.set",
            Self::TypedArrayProtoSlice => "TypedArray.prototype.slice",
            Self::TypedArrayProtoSubarray => "TypedArray.prototype.subarray",
            Self::BigInt64ArrayConstructor => "BigInt64Array",
            Self::BigUint64ArrayConstructor => "BigUint64Array",
            Self::TypedArrayProtoFill => "TypedArray.prototype.fill",
            Self::TypedArrayProtoReverse => "TypedArray.prototype.reverse",
            Self::TypedArrayProtoIndexOf => "TypedArray.prototype.indexOf",
            Self::TypedArrayProtoLastIndexOf => "TypedArray.prototype.lastIndexOf",
            Self::TypedArrayProtoIncludes => "TypedArray.prototype.includes",
            Self::TypedArrayProtoJoin => "TypedArray.prototype.join",
            Self::TypedArrayProtoToString => "TypedArray.prototype.toString",
            Self::TypedArrayProtoCopyWithin => "TypedArray.prototype.copyWithin",
            Self::TypedArrayProtoAt => "TypedArray.prototype.at",
            Self::TypedArrayProtoForEach => "TypedArray.prototype.forEach",
            Self::TypedArrayProtoMap => "TypedArray.prototype.map",
            Self::TypedArrayProtoFilter => "TypedArray.prototype.filter",
            Self::TypedArrayProtoReduce => "TypedArray.prototype.reduce",
            Self::TypedArrayProtoReduceRight => "TypedArray.prototype.reduceRight",
            Self::TypedArrayProtoFind => "TypedArray.prototype.find",
            Self::TypedArrayProtoFindIndex => "TypedArray.prototype.findIndex",
            Self::TypedArrayProtoSome => "TypedArray.prototype.some",
            Self::TypedArrayProtoEvery => "TypedArray.prototype.every",
            Self::TypedArrayProtoSort => "TypedArray.prototype.sort",
            Self::TypedArrayProtoEntries => "TypedArray.prototype.entries",
            Self::TypedArrayProtoKeys => "TypedArray.prototype.keys",
            Self::TypedArrayProtoValues => "TypedArray.prototype.values",
            _ => return None,
        })
    }

    /// 杂项：全局辅助、异常、eval 桥接、参数对象、作用域记录、WHATWG 流
    fn fmt_misc_str(&self) -> Option<&'static str> {
        Some(match self {
            Self::GetBuiltinGlobal => "get_builtin_global",
            Self::CreateGlobalObject => "create_global_object",
            Self::CreateException => "create_exception",
            Self::ExceptionValue => "exception_value",
            Self::IsException => "is_exception",
            Self::NewTarget => "new.target",
            Self::CreateUnmappedArgumentsObject => "create_unmapped_arguments_object",
            Self::CreateMappedArgumentsObject => "create_mapped_arguments_object",
            Self::ScopeRecordCreate => "scope_record_create",
            Self::ScopeRecordAddBinding => "scope_record_add_binding",
            Self::EvalGetBinding => "eval_get_binding",
            Self::EvalSetBinding => "eval_set_binding",
            Self::EvalHasBinding => "eval_has_binding",
            Self::EvalSuperBase => "eval_super_base",
            Self::ScopeRecordSetMeta => "scope_record_set_meta",
            Self::ScopeRecordDestroy => "scope_record_destroy",
            Self::ReadableStreamConstructor => "ReadableStream",
            Self::WritableStreamConstructor => "WritableStream",
            Self::TransformStreamConstructor => "TransformStream",
            Self::CountQueuingStrategyConstructor => "CountQueuingStrategy",
            Self::ByteLengthQueuingStrategyConstructor => "ByteLengthQueuingStrategy",
            _ => return None,
        })
    }
}
