// register_xxx → define_xxx 模块
mod async_fn;
mod async_generator;
mod misc;
mod promise;
mod promise_combinators;
mod proxy_reflect;
mod proxy_reflect_async;
mod reentrant_async;

pub(crate) use async_fn::define_async_fn;
pub(crate) use async_generator::define_async_generator;
pub(crate) use misc::define_misc;
pub(crate) use promise::define_promise;
pub(crate) use promise_combinators::define_promise_combinators;
pub(crate) use proxy_reflect::define_proxy_reflect;
pub(crate) use proxy_reflect_async::define_proxy_reflect_async;
pub(crate) use reentrant_async::define_array_object_async;
pub(crate) use reentrant_async::define_misc_async;
pub(crate) use reentrant_async::define_primitive_core_async;
pub(crate) use reentrant_async::define_proxy_traps_async;
pub(crate) use reentrant_async::define_timers_arrays_async;
pub(crate) use reentrant_async::define_typedarray_new_methods_async;
mod object_builtins;
pub(crate) use object_builtins::define_object_builtins;
mod object_builtins_async;
pub(crate) use object_builtins_async::define_object_builtins_async;
mod core_async;
mod get_method;
pub(crate) use get_method::get_method_by_name_id;
pub(crate) use core_async::define_core_async;

// 原 include! 裸块文件 → 模块声明
mod array_object;
mod atomics;
mod collections_buffers;
mod core;
mod fetch;
mod fetch_core;
mod fetch_http;
mod get_builtin_global_entry;
mod math_number_error;
mod primitive_core;
mod proxy_traps;
mod streams_queuing;
mod streams_readable;
mod streams_transform;
mod streams_writable;
mod string_methods;
mod timers_arrays;
mod typedarray_new_methods;
mod weakref_finalization;

pub(crate) use array_object::define_array_object;
pub(crate) use atomics::define_atomics;
pub(crate) use collections_buffers::define_collections_buffers;
pub(crate) use core::define_core;
pub(crate) use fetch::define_fetch;
pub(crate) use fetch_core::abort_controller_abort;
pub(crate) use fetch_core::call_headers_method_from_caller;
pub(crate) use fetch_core::call_reader_method_from_caller;
pub(crate) use fetch_core::call_request_method_from_caller;
pub(crate) use fetch_core::call_response_method_from_caller;
pub(crate) use fetch_core::call_stream_method_from_caller;
pub(crate) use fetch_core::construct_abort_controller;
pub(crate) use fetch_core::construct_headers;
pub(crate) use fetch_core::construct_request;
pub(crate) use fetch_core::construct_response;
pub(crate) use get_builtin_global_entry::define_get_builtin_global;
pub(crate) use math_number_error::define_math_number_error;
pub(crate) use primitive_core::define_primitive_core;
pub(crate) use proxy_traps::define_proxy_traps;
pub(crate) use streams_queuing::call_queuing_strategy_size_from_caller;
pub(crate) use streams_queuing::construct_byte_length_queuing_strategy;
pub(crate) use streams_queuing::construct_count_queuing_strategy;
pub(crate) use streams_readable::build_reader_result;
pub(crate) use streams_readable::build_reader_result_with_env;
pub(crate) use streams_readable::call_default_controller_method_from_caller;
pub(crate) use streams_readable::call_default_reader_method_from_caller;
pub(crate) use streams_readable::call_readable_stream_method_from_caller;
pub(crate) use streams_readable::construct_readable_stream;
pub(crate) use streams_transform::call_flush_from_writable_close;
pub(crate) use streams_transform::call_transform_from_writable;
pub(crate) use streams_transform::call_transform_stream_method_from_caller;
pub(crate) use streams_transform::construct_transform_stream;
pub(crate) use streams_writable::call_default_writer_method_from_caller;
pub(crate) use streams_writable::call_writable_controller_method_from_caller;
pub(crate) use streams_writable::call_writable_stream_method_from_caller;
pub(crate) use streams_writable::construct_writable_stream;
pub(crate) use string_methods::define_string_methods;
pub(crate) use timers_arrays::define_timers_arrays;
pub(crate) use typedarray_new_methods::define_typedarray_new_methods;
pub(crate) use weakref_finalization::define_weakref_finalization;
