[package]
name = "wjsm-gc"
version.workspace = true
edition.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }

[dependencies]
wjsm-ir = { path = "../wjsm-ir" }
parking_lot = "0.12"
crossbeam-deque = "0.8.6"
hdrhistogram = { workspace = true, default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_System_Threading"] }

[dev-dependencies]
anyhow = { workspace = true }
loom = "0.7"
